interface PrivacyContent {
  title: string;
  effective: string;
  intro: string;
  collectTitle: string;
  collectIntro: string;
  collectEmail: string;
  collectUsername: string;
  collectAvatar: string;
  collectLists: string;
  collectNoTracking: string;
  useTitle: string;
  useDescription: string;
  thirdPartyTitle: string;
  thirdPartyIntro: string;
  thirdPartyExpo: string;
  thirdPartyGoogle: string;
  thirdPartyCloudinary: string;
  thirdPartyTMDB: string;
  storageTitle: string;
  storageDescription: string;
  deletionTitle: string;
  deletionDescription: string;
  childrenTitle: string;
  childrenDescription: string;
  changesTitle: string;
  changesDescription: string;
  contactTitle: string;
  contactDescription: string;
}

export const privacyContent: Record<string, PrivacyContent> = {
  fr: {
    title: 'Politique de confidentialité',
    effective: 'En vigueur depuis le 22 mars 2026',
    intro: 'Cette politique de confidentialité s\'applique à Poplist, une application mobile et web créée par Samuel Prigent. Poplist est un service gratuit qui vous permet de créer et partager des listes de films et séries.',
    collectTitle: 'Données collectées',
    collectIntro: 'Nous collectons uniquement les données nécessaires au fonctionnement de l\'application :',
    collectEmail: 'Adresse email (pour la création de compte et l\'authentification)',
    collectUsername: 'Nom d\'utilisateur (choisi par vous, affiché publiquement)',
    collectAvatar: 'Photo de profil (optionnelle, téléchargée par vous)',
    collectLists: 'Vos listes et leur contenu (films et séries que vous ajoutez)',
    collectNoTracking: 'Nous n\'utilisons pas de cookies de suivi. Nous n\'utilisons aucun service d\'analyse. Nous ne collectons pas votre localisation, vos contacts, ni aucune donnée au-delà de ce qui est listé ci-dessus.',
    useTitle: 'Utilisation des données',
    useDescription: 'Vos données sont utilisées exclusivement pour fournir le service Poplist : authentifier votre compte, afficher vos listes et permettre les fonctionnalités de collaboration. Nous ne vendons, ne partageons et ne transmettons vos données à aucun tiers à des fins publicitaires ou d\'analyse.',
    thirdPartyTitle: 'Services tiers',
    thirdPartyIntro: 'L\'application utilise les services tiers suivants :',
    thirdPartyExpo: 'Expo — framework de l\'application mobile et livraison des mises à jour',
    thirdPartyGoogle: 'Google OAuth — authentification (nous recevons uniquement votre email, aucune autre donnée Google)',
    thirdPartyCloudinary: 'Cloudinary — hébergement des images de profil et des couvertures de listes',
    thirdPartyTMDB: 'TMDB — métadonnées des films et séries (aucune donnée utilisateur n\'est partagée avec TMDB)',
    storageTitle: 'Stockage et sécurité',
    storageDescription: 'Vos données sont stockées dans une base de données sécurisée. Toutes les communications entre l\'application et nos serveurs sont chiffrées via HTTPS. Les jetons d\'authentification sont stockés de manière sécurisée sur votre appareil.',
    deletionTitle: 'Suppression des données',
    deletionDescription: 'Vous pouvez supprimer votre compte à tout moment depuis les paramètres de l\'application. Cela supprime définitivement toutes vos données, y compris votre profil, vos listes et le contenu associé. Vous pouvez également demander la suppression de vos données en contactant',
    childrenTitle: 'Enfants',
    childrenDescription: 'Poplist ne s\'adresse pas aux enfants de moins de 13 ans. Nous ne collectons pas sciemment d\'informations personnelles auprès d\'enfants de moins de 13 ans.',
    changesTitle: 'Modifications',
    changesDescription: 'Cette politique de confidentialité peut être mise à jour de temps à autre. Les modifications seront reflétées sur cette page.',
    contactTitle: 'Contact',
    contactDescription: 'Pour toute question concernant cette politique, contactez',
  },
  en: {
    title: 'Privacy Policy',
    effective: 'Effective: March 22, 2026',
    intro: 'This privacy policy applies to Poplist, a mobile and web application created by Samuel Prigent. Poplist is a free service that lets you create and share movie and TV show lists.',
    collectTitle: 'What We Collect',
    collectIntro: 'We only collect the data necessary for the application to function:',
    collectEmail: 'Email address (for account creation and authentication)',
    collectUsername: 'Username (chosen by you, displayed publicly)',
    collectAvatar: 'Profile picture (optional, uploaded by you)',
    collectLists: 'Your lists and their content (movies, TV shows you add)',
    collectNoTracking: 'We do not use cookies for tracking. We do not use any analytics service. We do not collect your location, contacts, or any data beyond what is listed above.',
    useTitle: 'How We Use Your Data',
    useDescription: 'Your data is used exclusively to provide the Poplist service: authenticating your account, displaying your lists, and enabling collaboration features. We do not sell, share, or transmit your data to any third party for advertising or analytics purposes.',
    thirdPartyTitle: 'Third Party Services',
    thirdPartyIntro: 'The application uses the following third-party services:',
    thirdPartyExpo: 'Expo — mobile app framework and update delivery',
    thirdPartyGoogle: 'Google OAuth — authentication (we only receive your email, no other Google data)',
    thirdPartyCloudinary: 'Cloudinary — image hosting for profile pictures and list covers',
    thirdPartyTMDB: 'TMDB — movie and TV show metadata (no user data is shared with TMDB)',
    storageTitle: 'Data Storage and Security',
    storageDescription: 'Your data is stored in a secure database. All communications between the app and our servers are encrypted via HTTPS. Authentication tokens are stored securely on your device.',
    deletionTitle: 'Data Deletion',
    deletionDescription: 'You can delete your account at any time from the app settings. This permanently removes all your data including your profile, lists, and associated content. You can also request data deletion by contacting',
    childrenTitle: 'Children',
    childrenDescription: 'Poplist is not directed at children under 13. We do not knowingly collect personal information from children under 13.',
    changesTitle: 'Changes',
    changesDescription: 'This Privacy Policy may be updated from time to time. Changes will be reflected on this page.',
    contactTitle: 'Contact',
    contactDescription: 'For any questions regarding this policy, contact',
  },
  de: {
    title: 'Datenschutzrichtlinie',
    effective: 'Gültig ab: 22. März 2026',
    intro: 'Diese Datenschutzrichtlinie gilt für Poplist, eine mobile und Web-Anwendung, die von Samuel Prigent erstellt wurde. Poplist ist ein kostenloser Dienst, mit dem Sie Film- und Serienlisten erstellen und teilen können.',
    collectTitle: 'Welche Daten wir erheben',
    collectIntro: 'Wir erheben nur die für den Betrieb der Anwendung notwendigen Daten:',
    collectEmail: 'E-Mail-Adresse (für Kontoerstellung und Authentifizierung)',
    collectUsername: 'Benutzername (von Ihnen gewählt, öffentlich angezeigt)',
    collectAvatar: 'Profilbild (optional, von Ihnen hochgeladen)',
    collectLists: 'Ihre Listen und deren Inhalt (Filme und Serien, die Sie hinzufügen)',
    collectNoTracking: 'Wir verwenden keine Tracking-Cookies. Wir verwenden keinen Analysedienst. Wir erfassen nicht Ihren Standort, Ihre Kontakte oder andere Daten als die oben aufgeführten.',
    useTitle: 'Verwendung Ihrer Daten',
    useDescription: 'Ihre Daten werden ausschließlich zur Bereitstellung des Poplist-Dienstes verwendet: Authentifizierung Ihres Kontos, Anzeige Ihrer Listen und Ermöglichung von Zusammenarbeitsfunktionen. Wir verkaufen, teilen oder übermitteln Ihre Daten nicht an Dritte zu Werbe- oder Analysezwecken.',
    thirdPartyTitle: 'Drittanbieterdienste',
    thirdPartyIntro: 'Die Anwendung nutzt folgende Drittanbieterdienste:',
    thirdPartyExpo: 'Expo — Framework der mobilen App und Update-Bereitstellung',
    thirdPartyGoogle: 'Google OAuth — Authentifizierung (wir erhalten nur Ihre E-Mail, keine anderen Google-Daten)',
    thirdPartyCloudinary: 'Cloudinary — Bildhosting für Profilbilder und Listencover',
    thirdPartyTMDB: 'TMDB — Film- und Serienmetadaten (keine Benutzerdaten werden mit TMDB geteilt)',
    storageTitle: 'Datenspeicherung und Sicherheit',
    storageDescription: 'Ihre Daten werden in einer sicheren Datenbank gespeichert. Die gesamte Kommunikation zwischen der App und unseren Servern ist über HTTPS verschlüsselt. Authentifizierungstoken werden sicher auf Ihrem Gerät gespeichert.',
    deletionTitle: 'Datenlöschung',
    deletionDescription: 'Sie können Ihr Konto jederzeit in den App-Einstellungen löschen. Dadurch werden alle Ihre Daten einschließlich Ihres Profils, Ihrer Listen und zugehörigen Inhalte dauerhaft gelöscht. Sie können die Datenlöschung auch beantragen, indem Sie uns kontaktieren unter',
    childrenTitle: 'Kinder',
    childrenDescription: 'Poplist richtet sich nicht an Kinder unter 13 Jahren. Wir erfassen wissentlich keine persönlichen Daten von Kindern unter 13 Jahren.',
    changesTitle: 'Änderungen',
    changesDescription: 'Diese Datenschutzrichtlinie kann von Zeit zu Zeit aktualisiert werden. Änderungen werden auf dieser Seite wiedergegeben.',
    contactTitle: 'Kontakt',
    contactDescription: 'Bei Fragen zu dieser Richtlinie kontaktieren Sie',
  },
  es: {
    title: 'Política de Privacidad',
    effective: 'Vigente desde: 22 de marzo de 2026',
    intro: 'Esta política de privacidad se aplica a Poplist, una aplicación móvil y web creada por Samuel Prigent. Poplist es un servicio gratuito que permite crear y compartir listas de películas y series.',
    collectTitle: 'Datos que recopilamos',
    collectIntro: 'Solo recopilamos los datos necesarios para el funcionamiento de la aplicación:',
    collectEmail: 'Dirección de correo electrónico (para la creación de cuenta y autenticación)',
    collectUsername: 'Nombre de usuario (elegido por usted, mostrado públicamente)',
    collectAvatar: 'Foto de perfil (opcional, subida por usted)',
    collectLists: 'Sus listas y su contenido (películas y series que añade)',
    collectNoTracking: 'No utilizamos cookies de seguimiento. No utilizamos ningún servicio de análisis. No recopilamos su ubicación, contactos ni ningún dato más allá de lo indicado anteriormente.',
    useTitle: 'Uso de sus datos',
    useDescription: 'Sus datos se utilizan exclusivamente para proporcionar el servicio Poplist: autenticar su cuenta, mostrar sus listas y permitir las funciones de colaboración. No vendemos, compartimos ni transmitimos sus datos a terceros con fines publicitarios o de análisis.',
    thirdPartyTitle: 'Servicios de terceros',
    thirdPartyIntro: 'La aplicación utiliza los siguientes servicios de terceros:',
    thirdPartyExpo: 'Expo — framework de la aplicación móvil y entrega de actualizaciones',
    thirdPartyGoogle: 'Google OAuth — autenticación (solo recibimos su correo electrónico, ningún otro dato de Google)',
    thirdPartyCloudinary: 'Cloudinary — alojamiento de imágenes para fotos de perfil y portadas de listas',
    thirdPartyTMDB: 'TMDB — metadatos de películas y series (no se comparten datos de usuario con TMDB)',
    storageTitle: 'Almacenamiento y seguridad',
    storageDescription: 'Sus datos se almacenan en una base de datos segura. Todas las comunicaciones entre la aplicación y nuestros servidores están cifradas mediante HTTPS. Los tokens de autenticación se almacenan de forma segura en su dispositivo.',
    deletionTitle: 'Eliminación de datos',
    deletionDescription: 'Puede eliminar su cuenta en cualquier momento desde los ajustes de la aplicación. Esto elimina permanentemente todos sus datos, incluyendo su perfil, listas y contenido asociado. También puede solicitar la eliminación de sus datos contactando a',
    childrenTitle: 'Menores',
    childrenDescription: 'Poplist no está dirigido a menores de 13 años. No recopilamos conscientemente información personal de menores de 13 años.',
    changesTitle: 'Cambios',
    changesDescription: 'Esta Política de Privacidad puede actualizarse de vez en cuando. Los cambios se reflejarán en esta página.',
    contactTitle: 'Contacto',
    contactDescription: 'Para cualquier pregunta sobre esta política, contacte a',
  },
  it: {
    title: 'Informativa sulla Privacy',
    effective: 'In vigore dal: 22 marzo 2026',
    intro: 'Questa informativa sulla privacy si applica a Poplist, un\'applicazione mobile e web creata da Samuel Prigent. Poplist è un servizio gratuito che consente di creare e condividere liste di film e serie TV.',
    collectTitle: 'Dati raccolti',
    collectIntro: 'Raccogliamo solo i dati necessari al funzionamento dell\'applicazione:',
    collectEmail: 'Indirizzo email (per la creazione dell\'account e l\'autenticazione)',
    collectUsername: 'Nome utente (scelto da te, visualizzato pubblicamente)',
    collectAvatar: 'Foto profilo (opzionale, caricata da te)',
    collectLists: 'Le tue liste e il loro contenuto (film e serie che aggiungi)',
    collectNoTracking: 'Non utilizziamo cookie di tracciamento. Non utilizziamo alcun servizio di analisi. Non raccogliamo la tua posizione, i tuoi contatti o altri dati oltre a quelli sopra elencati.',
    useTitle: 'Utilizzo dei dati',
    useDescription: 'I tuoi dati vengono utilizzati esclusivamente per fornire il servizio Poplist: autenticare il tuo account, visualizzare le tue liste e abilitare le funzionalità di collaborazione. Non vendiamo, condividiamo o trasmettiamo i tuoi dati a terzi per scopi pubblicitari o di analisi.',
    thirdPartyTitle: 'Servizi di terze parti',
    thirdPartyIntro: 'L\'applicazione utilizza i seguenti servizi di terze parti:',
    thirdPartyExpo: 'Expo — framework dell\'app mobile e distribuzione degli aggiornamenti',
    thirdPartyGoogle: 'Google OAuth — autenticazione (riceviamo solo la tua email, nessun altro dato Google)',
    thirdPartyCloudinary: 'Cloudinary — hosting delle immagini per foto profilo e copertine delle liste',
    thirdPartyTMDB: 'TMDB — metadati di film e serie (nessun dato utente viene condiviso con TMDB)',
    storageTitle: 'Archiviazione e sicurezza',
    storageDescription: 'I tuoi dati sono archiviati in un database sicuro. Tutte le comunicazioni tra l\'app e i nostri server sono crittografate tramite HTTPS. I token di autenticazione sono archiviati in modo sicuro sul tuo dispositivo.',
    deletionTitle: 'Cancellazione dei dati',
    deletionDescription: 'Puoi eliminare il tuo account in qualsiasi momento dalle impostazioni dell\'app. Questo rimuove permanentemente tutti i tuoi dati, incluso il profilo, le liste e i contenuti associati. Puoi anche richiedere la cancellazione dei dati contattando',
    childrenTitle: 'Minori',
    childrenDescription: 'Poplist non è destinato a minori di 13 anni. Non raccogliamo consapevolmente informazioni personali da minori di 13 anni.',
    changesTitle: 'Modifiche',
    changesDescription: 'Questa Informativa sulla Privacy può essere aggiornata di tanto in tanto. Le modifiche saranno riportate su questa pagina.',
    contactTitle: 'Contatto',
    contactDescription: 'Per qualsiasi domanda riguardo questa informativa, contattare',
  },
  pt: {
    title: 'Política de Privacidade',
    effective: 'Em vigor desde: 22 de março de 2026',
    intro: 'Esta política de privacidade aplica-se ao Poplist, uma aplicação móvel e web criada por Samuel Prigent. O Poplist é um serviço gratuito que permite criar e partilhar listas de filmes e séries.',
    collectTitle: 'Dados recolhidos',
    collectIntro: 'Recolhemos apenas os dados necessários ao funcionamento da aplicação:',
    collectEmail: 'Endereço de email (para criação de conta e autenticação)',
    collectUsername: 'Nome de utilizador (escolhido por si, exibido publicamente)',
    collectAvatar: 'Foto de perfil (opcional, carregada por si)',
    collectLists: 'As suas listas e o seu conteúdo (filmes e séries que adiciona)',
    collectNoTracking: 'Não utilizamos cookies de rastreamento. Não utilizamos nenhum serviço de análise. Não recolhemos a sua localização, contactos ou quaisquer outros dados além dos listados acima.',
    useTitle: 'Utilização dos dados',
    useDescription: 'Os seus dados são utilizados exclusivamente para fornecer o serviço Poplist: autenticar a sua conta, exibir as suas listas e permitir funcionalidades de colaboração. Não vendemos, partilhamos ou transmitimos os seus dados a terceiros para fins publicitários ou de análise.',
    thirdPartyTitle: 'Serviços de terceiros',
    thirdPartyIntro: 'A aplicação utiliza os seguintes serviços de terceiros:',
    thirdPartyExpo: 'Expo — framework da aplicação móvel e entrega de atualizações',
    thirdPartyGoogle: 'Google OAuth — autenticação (recebemos apenas o seu email, nenhum outro dado do Google)',
    thirdPartyCloudinary: 'Cloudinary — alojamento de imagens para fotos de perfil e capas de listas',
    thirdPartyTMDB: 'TMDB — metadados de filmes e séries (nenhum dado de utilizador é partilhado com o TMDB)',
    storageTitle: 'Armazenamento e segurança',
    storageDescription: 'Os seus dados são armazenados numa base de dados segura. Todas as comunicações entre a aplicação e os nossos servidores são encriptadas via HTTPS. Os tokens de autenticação são armazenados de forma segura no seu dispositivo.',
    deletionTitle: 'Eliminação de dados',
    deletionDescription: 'Pode eliminar a sua conta a qualquer momento nas definições da aplicação. Isto remove permanentemente todos os seus dados, incluindo o seu perfil, listas e conteúdo associado. Também pode solicitar a eliminação dos seus dados contactando',
    childrenTitle: 'Menores',
    childrenDescription: 'O Poplist não se destina a menores de 13 anos. Não recolhemos conscientemente informações pessoais de menores de 13 anos.',
    changesTitle: 'Alterações',
    changesDescription: 'Esta Política de Privacidade pode ser atualizada de tempos a tempos. As alterações serão refletidas nesta página.',
    contactTitle: 'Contacto',
    contactDescription: 'Para qualquer questão sobre esta política, contacte',
  },
};
