/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as HomeRouteImport } from './routes/home'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ListsIndexRouteImport } from './routes/lists/index'
import { Route as CategoriesIndexRouteImport } from './routes/categories/index'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as UserUsernameRouteImport } from './routes/user/$username'
import { Route as LocalListsRouteImport } from './routes/local/lists'
import { Route as ListsIdRouteImport } from './routes/lists/$id'
import { Route as CategoriesIdRouteImport } from './routes/categories/$id'
import { Route as AccountListsRouteImport } from './routes/account/lists'
import { Route as LocalListIdRouteImport } from './routes/local/list/$id'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListsIndexRoute = ListsIndexRouteImport.update({
  id: '/lists/',
  path: '/lists/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesIndexRoute = CategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserUsernameRoute = UserUsernameRouteImport.update({
  id: '/user/$username',
  path: '/user/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalListsRoute = LocalListsRouteImport.update({
  id: '/local/lists',
  path: '/local/lists',
  getParentRoute: () => rootRouteImport,
} as any)
const ListsIdRoute = ListsIdRouteImport.update({
  id: '/lists/$id',
  path: '/lists/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesIdRoute = CategoriesIdRouteImport.update({
  id: '/categories/$id',
  path: '/categories/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountListsRoute = AccountListsRouteImport.update({
  id: '/account/lists',
  path: '/account/lists',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalListIdRoute = LocalListIdRouteImport.update({
  id: '/local/list/$id',
  path: '/local/list/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/home': typeof HomeRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/users': typeof UsersRoute
  '/account/lists': typeof AccountListsRoute
  '/categories/$id': typeof CategoriesIdRoute
  '/lists/$id': typeof ListsIdRoute
  '/local/lists': typeof LocalListsRoute
  '/user/$username': typeof UserUsernameRoute
  '/account/': typeof AccountIndexRoute
  '/categories/': typeof CategoriesIndexRoute
  '/lists/': typeof ListsIndexRoute
  '/local/list/$id': typeof LocalListIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/home': typeof HomeRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/users': typeof UsersRoute
  '/account/lists': typeof AccountListsRoute
  '/categories/$id': typeof CategoriesIdRoute
  '/lists/$id': typeof ListsIdRoute
  '/local/lists': typeof LocalListsRoute
  '/user/$username': typeof UserUsernameRoute
  '/account': typeof AccountIndexRoute
  '/categories': typeof CategoriesIndexRoute
  '/lists': typeof ListsIndexRoute
  '/local/list/$id': typeof LocalListIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/home': typeof HomeRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/users': typeof UsersRoute
  '/account/lists': typeof AccountListsRoute
  '/categories/$id': typeof CategoriesIdRoute
  '/lists/$id': typeof ListsIdRoute
  '/local/lists': typeof LocalListsRoute
  '/user/$username': typeof UserUsernameRoute
  '/account/': typeof AccountIndexRoute
  '/categories/': typeof CategoriesIndexRoute
  '/lists/': typeof ListsIndexRoute
  '/local/list/$id': typeof LocalListIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/explore'
    | '/home'
    | '/privacy'
    | '/sitemap.xml'
    | '/users'
    | '/account/lists'
    | '/categories/$id'
    | '/lists/$id'
    | '/local/lists'
    | '/user/$username'
    | '/account/'
    | '/categories/'
    | '/lists/'
    | '/local/list/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/explore'
    | '/home'
    | '/privacy'
    | '/sitemap.xml'
    | '/users'
    | '/account/lists'
    | '/categories/$id'
    | '/lists/$id'
    | '/local/lists'
    | '/user/$username'
    | '/account'
    | '/categories'
    | '/lists'
    | '/local/list/$id'
  id:
    | '__root__'
    | '/'
    | '/explore'
    | '/home'
    | '/privacy'
    | '/sitemap.xml'
    | '/users'
    | '/account/lists'
    | '/categories/$id'
    | '/lists/$id'
    | '/local/lists'
    | '/user/$username'
    | '/account/'
    | '/categories/'
    | '/lists/'
    | '/local/list/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExploreRoute: typeof ExploreRoute
  HomeRoute: typeof HomeRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UsersRoute: typeof UsersRoute
  AccountListsRoute: typeof AccountListsRoute
  CategoriesIdRoute: typeof CategoriesIdRoute
  ListsIdRoute: typeof ListsIdRoute
  LocalListsRoute: typeof LocalListsRoute
  UserUsernameRoute: typeof UserUsernameRoute
  AccountIndexRoute: typeof AccountIndexRoute
  CategoriesIndexRoute: typeof CategoriesIndexRoute
  ListsIndexRoute: typeof ListsIndexRoute
  LocalListIdRoute: typeof LocalListIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lists/': {
      id: '/lists/'
      path: '/lists'
      fullPath: '/lists/'
      preLoaderRoute: typeof ListsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/': {
      id: '/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof CategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$username': {
      id: '/user/$username'
      path: '/user/$username'
      fullPath: '/user/$username'
      preLoaderRoute: typeof UserUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/local/lists': {
      id: '/local/lists'
      path: '/local/lists'
      fullPath: '/local/lists'
      preLoaderRoute: typeof LocalListsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lists/$id': {
      id: '/lists/$id'
      path: '/lists/$id'
      fullPath: '/lists/$id'
      preLoaderRoute: typeof ListsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$id': {
      id: '/categories/$id'
      path: '/categories/$id'
      fullPath: '/categories/$id'
      preLoaderRoute: typeof CategoriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/lists': {
      id: '/account/lists'
      path: '/account/lists'
      fullPath: '/account/lists'
      preLoaderRoute: typeof AccountListsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/local/list/$id': {
      id: '/local/list/$id'
      path: '/local/list/$id'
      fullPath: '/local/list/$id'
      preLoaderRoute: typeof LocalListIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExploreRoute: ExploreRoute,
  HomeRoute: HomeRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UsersRoute: UsersRoute,
  AccountListsRoute: AccountListsRoute,
  CategoriesIdRoute: CategoriesIdRoute,
  ListsIdRoute: ListsIdRoute,
  LocalListsRoute: LocalListsRoute,
  UserUsernameRoute: UserUsernameRoute,
  AccountIndexRoute: AccountIndexRoute,
  CategoriesIndexRoute: CategoriesIndexRoute,
  ListsIndexRoute: ListsIndexRoute,
  LocalListIdRoute: LocalListIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
