import type { Content } from '@/types/content';

export const de: Content = {
  // Header
  header: {
    appName: 'Poplist',
    home: 'Startseite',
    explore: 'Erkunden',
    login: 'Anmelden',
    signup: 'Registrieren',
    logout: 'Abmelden',
    myLists: 'Meine Listen',
    categories: 'Kategorien',
  },

  // Auth Drawer
  auth: {
    loginTitle: 'Anmelden',
    loginDescription: 'Willkommen zurück! Melde dich an, um auf deine Listen zuzugreifen.',
    signupTitle: 'Registrieren',
    signupDescription: 'Erstelle ein Konto, um deine Listen zu speichern.',
    continueWithGoogle: 'Mit Google fortfahren',
    or: 'Oder',
    email: 'E-Mail',
    emailPlaceholder: 'ihre@email.de',
    password: 'Passwort',
    passwordPlaceholder: 'Dein Passwort',
    processing: 'Wird verarbeitet...',
    dontHaveAccount: 'Noch kein Konto?',
    alreadyHaveAccount: 'Bereits ein Konto?',
  },

  // Watchlists Page
  watchlists: {
    title: 'Bibliothek',
    createWatchlist: 'Neue Liste',
    createWatchlistDescription:
      'Erstelle eine neue Liste, um deine Filme und Serien zu organisieren.',
    noWatchlistsMobile: 'Keine Liste',
    createWatchlistDescriptionMobile: 'Erstelle deine erste Liste.',
    noWatchlists: 'Du hast noch keine Listen erstellt.',
    signupCta: {
      title: 'Erstelle ein Konto',
      description: 'Erstelle Film- und Serienlisten und teile sie mit der Community.',
      button: 'Registrieren',
    },
    myWatchlists: 'Meine Listen',
    followed: 'Gefolgt',
    noWatchlistsInCategory: 'Keine Listen in dieser Kategorie',
    adjustFilters: 'Passe die Filter an, um mehr Listen zu sehen',
    items: 'Elemente',
    item: 'Element',
    by: 'von',
    saveCount: 'Speicherung',
    savesCount: 'Speicherungen',
    loading: 'Lädt...',
    accountDataBadge: 'Benutzerkontodaten',
    preview: 'Vorschau',
    categories: 'Kategorien / Tags',
    categoriesDescription:
      'Wähle eine oder mehrere Kategorien aus, um deine Liste leichter auffindbar zu machen',
    genreCategories: 'Genre-Kategorien',
    platformCategories: 'Streaming-Plattformen',
    platformsDescription: 'Wähle die Plattformen aus, auf denen deine Liste verfügbar ist',
    name: 'Name',
    namePlaceholder: 'Meine Liste',
    description: 'Beschreibung',
    descriptionPlaceholder: 'Beschreibung deiner Liste',
    coverImage: 'Titelbild',
    uploadImage: 'Bild hochladen',
    changeImage: 'Bild ändern',
    imageUploadHint: 'PNG, JPG oder WEBP (max. 5MB)',
    removeImage: 'Cover entfernen',
    cancel: 'Abbrechen',
    create: 'Erstellen',
    creating: 'Wird erstellt...',
    back: 'Zurück',
    noItemsYet: 'Noch keine Elemente',
    noItemsDescription:
      'Beginne damit, Filme und Serien zu deiner Liste hinzuzufügen, um deine Warteschlange zu organisieren.',
    edit: 'Bearbeiten',
    editWatchlist: 'Liste bearbeiten',
    editWatchlistDescription: 'Bearbeite die Informationen deiner Liste.',
    deleteWatchlist: 'Liste löschen',
    deleteWatchlistConfirm:
      'Möchtest du "{name}" wirklich löschen? Diese Aktion kann nicht rückgängig gemacht werden.',
    deleteWatchlistWarning:
      'Diese Liste enthält {count} Element(e), die ebenfalls gelöscht werden.',
    saving: 'Wird gespeichert...',
    save: 'Speichern',
    deleting: 'Wird gelöscht...',
    delete: 'Löschen',
    addItem: 'Hinzufügen',
    searchMoviesAndSeries: 'Suche Filme oder Serien und füge sie deiner Liste hinzu',
    searchPlaceholder: 'Nach einem Film oder einer Serie suchen...',
    searching: 'Sucht...',
    noResults: 'Keine Ergebnisse gefunden',
    startSearching: 'Beginne mit der Eingabe, um nach Filmen und Serien zu suchen',
    add: 'Hinzufügen',
    added: 'Hinzugefügt',
    inWatchlist: 'In Liste',
    recommendations: {
      title: 'Empfohlen',
      similarTitle: 'Ähnliche Inhalte',
      subtitle: 'Basierend auf dem Inhalt dieser Liste',
      refresh: 'Aktualisieren',
    },
    // Table headers
    tableHeaders: {
      number: '#',
      title: 'Titel',
      type: 'Typ',
      platforms: 'Plattformen',
      duration: 'Dauer',
    },
    // Content types
    contentTypes: {
      movie: 'Film',
      series: 'Serie',
    },
    // Series info
    seriesInfo: {
      season: 'Staffel',
      seasons: 'Staffeln',
      episodes: 'Episoden',
    },
    // Item Details Modal
    itemDetails: {
      loading: 'Lädt...',
      error: 'Fehler beim Laden der Details',
      mediaDetails: 'Mediendetails',
      fullDetailsFor: 'Vollständige Details für',
      loadingDetails: 'Details werden geladen',
      notAvailable: 'N/V',
      votes: 'Stimmen',
      synopsis: 'Zusammenfassung',
      director: 'Regisseur',
      creator: 'Schöpfer',
      availableOn: 'Verfügbar auf',
      availableShort: 'Verfügbar',
      mainCast: 'Hauptbesetzung',
      seeMore: 'Mehr sehen',
      seeLess: 'Weniger anzeigen',
    },
    tooltips: {
      share: 'Teilen',
      save: 'Zur Bibliothek hinzufügen',
      unsave: 'Aus Bibliothek entfernen',
      duplicate: 'In meinen Bereich duplizieren',
      inviteCollaborator: 'Mitarbeiter einladen',
    },
    contextMenu: {
      addToWatchlist: 'Zu Liste hinzufügen',
      removeFromWatchlist: 'Aus Liste entfernen',
      moveToFirst: 'An erste Position verschieben',
      moveToLast: 'An letzte Position verschieben',
    },
    collaborators: {
      addTitle: 'Mitarbeiter hinzufügen',
      addDescription: 'Benutzername des Mitarbeiters eingeben',
      usernamePlaceholder: 'Benutzername',
      add: 'Hinzufügen',
      adding: 'Wird hinzugefügt...',
      addSuccess: 'Mitarbeiter erfolgreich hinzugefügt',
      addError: 'Mitarbeiter konnte nicht hinzugefügt werden',
      currentTitle: 'Aktuelle Mitarbeiter',
      remove: 'Entfernen',
      removeSuccess: 'Mitarbeiter entfernt',
      removeError: 'Mitarbeiter konnte nicht entfernt werden',
      leaveTitle: 'Liste verlassen?',
      leaveDescription:
        'Möchtest du diese Liste wirklich verlassen? Du verlierst deine Mitarbeiterrechte.',
      leave: 'Verlassen',
      leaving: 'Wird verlassen...',
      leaveSuccess: 'Du hast die Liste verlassen',
      leaveError: 'Liste konnte nicht verlassen werden',
    },
    addToWatchlist: 'Zu einer Liste hinzufügen',
    noWatchlist: 'Keine Liste',
    toasts: {
      linkCopied: 'Link kopiert',
      linkCopyError: 'Link konnte nicht kopiert werden',
      listSaved: 'Liste hinzugefügt',
      listUnsaved: 'Liste entfernt',
      listSaveError: 'Liste konnte nicht aktualisiert werden',
      duplicating: 'Wird dupliziert...',
      listDuplicated: 'Liste dupliziert',
      duplicateError: 'Liste konnte nicht dupliziert werden',
      itemAdded: 'Zur Liste hinzugefügt',
      itemRemoved: 'Von der Liste entfernt',
      itemAddError: 'Hinzufügen fehlgeschlagen, bitte erneut versuchen',
      itemRemoveError: 'Entfernen fehlgeschlagen, bitte erneut versuchen',
    },
  },

  landing: {
    hero: {
      title: 'Erstelle und teile Listen deiner Lieblingsinhalte',
      subtitle:
        'Organisiere deine TV-Abende und teile deine Entdeckungen mit deinen Freunden',
      titleMobile: 'Erstelle Listen deiner Lieblingsinhalte',
      subtitleMobile: 'Plane deine TV-Abende',
    },
    features: {
      sectionTitle: 'Teile dein Filmuniversum',
      sectionTitleMobile: 'Unsere Funktionen',
      sectionSubtitle: 'Entdecke alle unsere Funktionen',
      organize: {
        tagline: 'Organisation',
        title: 'Listen erstellen',
        description: 'Erstelle persönliche Listen von Filmen und Serien.',
      },
      collaborate: {
        tagline: 'Zusammenarbeit',
        title: 'Mitarbeiter hinzufügen',
        description: 'Lade Freunde ein, in Echtzeit zu deinen Listen beizutragen.',
      },
      share: {
        tagline: 'Teilen',
        title: 'Listen teilen',
        description: 'Teile deine Listen mit einem einfachen Link an Freunde.',
      },
      discover: {
        tagline: 'Entdeckung',
        title: 'Community-Listen folgen',
        description: 'Entdecke und folge Listen anderer Benutzer.',
      },
    },
    startInSeconds: {
      title: 'In Sekunden starten',
      subtitle: 'Keine komplizierte Einrichtung, nur du und deine Lieblingsinhalte',
      step1: {
        title: 'Erstelle deine Liste',
        description: 'Benenne deine Liste und beginne zu organisieren.',
      },
      step2: {
        title: 'Filme hinzufügen',
        description: 'Füge Filme und Serien mit wenigen Klicks hinzu.',
      },
      step3: {
        title: 'Mit Freunden teilen',
        description: 'Ein Link genügt zum Teilen.',
      },
    },
    testimonials: {
      title: 'Beliebt bei Enthusiasten',
      titleMobile: 'Erfahrungsberichte',
      subtitle: 'Werde Teil einer Gemeinschaft zufriedener Nutzer',
      testimonial1: {
        text: 'Perfekte App zum Organisieren meiner Listen. Klare und intuitive Benutzeroberfläche.',
        author: 'Marie L.',
        pseudo: '@maried',
      },
      testimonial2: {
        text: 'Sehr praktisch! Hilft dabei, den Überblick zu behalten, was wir gesehen haben und was wir empfehlen möchten.',
        author: 'Thomas D.',
        pseudo: '@thomasdlm',
      },
      testimonial3: {
        text: 'Einfach, effektiv, genau das, was ich gesucht habe, um meine zu sehenden Filme zu verwalten.',
        author: 'Julie M.',
        pseudo: '@juliem',
      },
      testimonial4: {
        text: 'Das Teilen per Link hat mich überzeugt. Meine Freunde sehen meine Liste ohne Konto.',
        author: 'Karim B.',
        pseudo: '@karimb',
      },
      testimonial5: {
        text: 'Wir planen unsere Serienabende gemeinsam, jeder fügt der gleichen Liste etwas hinzu.',
        author: 'Léa P.',
        pseudo: '@leapasc',
      },
      testimonial6: {
        text: 'Endlich ein Ort für alles, was mir empfohlen wurde. Kein langes Suchen mehr.',
        author: 'Antoine R.',
        pseudo: '@antoiner',
      },
    },
    finalCta: {
      title: 'Beginne einfach mit der Erstellung deiner Listen',
      titleMobile: 'Werde Teil des Abenteuers',
      subtitle:
        'Komm zu Poplist und organisiere deine Lieblingsinhalte mit nur wenigen Klicks.',
      subtitleMobile: 'Tritt unserer Community bei',
      button: 'Meine Liste erstellen',
      disclaimer: 'Kostenlose Anwendung • Keine Karte erforderlich',
    },
  },

  // Home Page
  home: {
    hero: {
      title: 'Deine Listen perfekt organisiert',
      subtitle: 'Dein Film-Universum, organisiert und mit Freunden geteilt.',
      cta: 'Entdecken',
      ctaSecondary: 'Mehr erfahren',
      pills: {
        organize: 'Organisiere deine Filme',
        share: 'Mit Freunden teilen',
        discover: 'Entdecke Perlen',
      },
    },
    library: {
      title: 'Bibliothek',
      subtitle: 'Deine persönlichen Listen',
      seeAll: 'Alle anzeigen',
    },
    categories: {
      title: 'Listen nach Kategorie',
      subtitle: 'Poplist-Auswahl',
      seeMore: 'Mehr sehen',
      list: 'Liste',
      lists: 'Listen',
    },
    platformsSection: {
      title: 'Listen nach Plattform',
      subtitle: 'Deine Lieblingsplattformen',
      seeAll: 'Alle anzeigen',
    },
    popularWatchlists: {
      title: 'Beliebte Listen',
      subtitle: 'Von der Community geteilt',
      seeMore: 'Mehr sehen',
      noWatchlists: 'Momentan keine öffentlichen Listen',
      loadError: 'Die Listen konnten nicht geladen werden',
      retry: 'Erneut versuchen',
    },
    faq: {
      title: 'Häufig gestellte Fragen',
      subtitle: 'Die häufigsten Fragen zur Plattform: das Prinzip, unser Mehrwert und wie sie funktioniert.',
      questions: {
        pricing: {
          question: 'Ist die Nutzung kostenlos?',
          answer:
            'Ja, die App ist völlig kostenlos! Du kannst so viele Listen erstellen, wie du möchtest, sie mit deinen Freunden teilen und Tausende von Filmen und Serien ohne Gebühren erkunden.',
        },
        exploreSection: {
          question: 'Wofür ist der Bereich Erkunden?',
          answer:
            'Der Bereich Erkunden ermöglicht es dir, neue Inhalte zu entdecken, indem du aktuelle Trends, die beliebtesten oder am besten bewerteten Filme und Serien durchsuchst. Du kannst nach Genre filtern, um genau das zu finden, was du suchst, und Elemente direkt zu deinen Listen hinzufügen.',
        },
        whatMakesDifferent: {
          question: 'Was macht diese App anders?',
          answer:
            'Diese Anwendung zielt darauf ab, einfach zu bleiben mit wenigen Funktionen und Seiten, um klar und einfach zu bedienen zu sein. Die Erfahrung soll natürlich und intuitiv sein, ohne unnötige Komplexität. Wir konzentrieren uns auf das Wesentliche: deine Lieblingsfilme und -serien organisieren und teilen.',
        },
        streaming: {
          question: 'Kann ich Serien oder Filme ansehen?',
          answer:
            'Nein, der Zweck dieser Anwendung ist nicht das Streaming, sondern das einfache Teilen von Inhalten, die dir auf deinen Lieblingsplattformen gefallen haben. Wir helfen dir, zu organisieren, was du sehen möchtest, und es mit deiner Community zu teilen, aber um den Inhalt anzusehen, musst du zu den entsprechenden Streaming-Plattformen gehen.',
        },
      },
    },
    trending: {
      title: 'Heute im Trend',
      subtitle: 'Beliebte Filme und Serien des Moments',
      noImage: 'Kein Bild',
      seeMore: 'Alle anzeigen',
    },
    recommendations: {
      title: 'Gerade im Trend',
      subtitle: 'Die angesagtesten Titel dieser Woche.',
      seeMore: 'Alle anzeigen',
    },
    creators: {
      title: 'Unsere Ersteller',
      subtitle: 'Die aktivsten Mitglieder der Community',
      seeMore: 'Alle anzeigen',
    },
    communityWatchlists: {
      title: 'Community-Listen',
      subtitle: 'Entdecke von unseren Nutzern geteilte Sammlungen',
    },
  },

  explore: {
    title: 'Erkunden',
    subtitle: 'Entdecke neue Listen, die von der Community geteilt werden',
    searchPlaceholder: 'Nach einem Film oder einer Serie suchen...',
    filters: {
      all: 'Alle',
      movies: 'Filme',
      series: 'Serien',
      trending: 'Trends',
      topRated: 'Am besten bewertet',
      popular: 'Beliebt',
      bestRated: 'Am besten bewertet',
      yearMin: 'Mindestjahr',
      yearMax: 'Maximaljahr',
      search: 'Suchen...',
      noYearFound: 'Kein Jahr gefunden.',
      clearYears: 'Jahre löschen',
      genres: 'Genres',
      year: 'Jahr',
      apply: 'Anwenden',
    },
    genres: {
      action: 'Action',
      adventure: 'Abenteuer',
      animation: 'Animation',
      comedy: 'Komödie',
      crime: 'Krimi',
      documentary: 'Dokumentarfilm',
      drama: 'Drama',
      family: 'Familie',
      fantasy: 'Fantasy',
      horror: 'Horror',
      romance: 'Romantik',
      scienceFiction: 'Science-Fiction',
      thriller: 'Thriller',
      actionAdventure: 'Action & Abenteuer',
      kids: 'Kinder',
      mystery: 'Mystery',
      sciFiFantasy: 'Sci-Fi & Fantasy',
      soap: 'Seifenoper',
      western: 'Western',
    },
    sortBy: {
      label: 'Sortieren nach',
      popular: 'Am beliebtesten',
      recentlyAdded: 'Kürzlich hinzugefügt',
      mostItems: 'Meiste Elemente',
    },
    pagination: {
      pageOf: 'Seite {page} von {totalPages}',
    },
    noResults: 'Keine Listen gefunden',
    noResultsDescription: 'Versuche, deine Filter oder Suche anzupassen',
  },

  categories: {
    title: 'Kategorien',
    subtitle: 'Erkunde Listen nach Thema',
    list: {
      movies: { name: 'Filme', description: 'Die besten Filme des Moments' },
      series: {
        name: 'Serien',
        description: 'Serien, die du nicht verpassen solltest',
      },
      animation: {
        name: 'Animation',
        description: 'Die besten Animationsserien und -filme',
      },
      enfant: { name: 'Kinder', description: 'Filme und Serien für Kinder' },
      jeunesse: {
        name: 'Jugend',
        description: 'Filme und Serien für Jugendliche und junge Erwachsene',
      },
      documentaries: {
        name: 'Dokumentarfilme',
        description: 'Fesselnde und lehrreiche Dokumentarfilme',
      },
      action: { name: 'Action', description: 'Klassiker und neue Actionfilme' },
      anime: {
        name: 'Anime',
        description: 'Japanische Anime und adaptierte Manga',
      },
    },
  },

  // Footer
  footer: {
    appName: 'Poplist',
    language: 'Sprache',
  },

  // Profile Page
  profile: {
    title: 'Profileinstellungen',
    subtitle: 'Verwalte deine Kontoeinstellungen und Präferenzen',
    userInformation: 'Benutzerinformationen',
    avatarSection: {
      title: 'Profilbild',
      description: 'Lade ein Profilbild hoch, um dein Konto zu personalisieren',
      uploadButton: 'Hochladen',
      changeButton: 'Ändern',
      deleteButton: 'Löschen',
      uploading: 'Wird hochgeladen...',
      deleting: 'Wird gelöscht...',
      hint: 'Empfohlen: Quadratisches Bild, max. 5MB',
      validation: {
        invalidFileType: 'Bitte wähle eine gültige Bilddatei',
        fileTooLarge: 'Die Bildgröße muss weniger als 5MB betragen',
        uploadFailed: 'Fehler beim Hochladen des Avatars',
        deleteFailed: 'Fehler beim Löschen des Avatars',
        readFailed: 'Fehler beim Lesen der Bilddatei',
      },
      toasts: {
        updated: 'Avatar aktualisiert',
        updatedDesc: 'Dein Avatar wurde erfolgreich aktualisiert',
        deleted: 'Avatar gelöscht',
        deletedDesc: 'Dein Avatar wurde erfolgreich gelöscht',
      },
    },
    usernameSection: {
      title: 'Benutzername',
      description: 'Aktualisiere deinen Benutzernamen. So wirst du von anderen gesehen.',
      label: 'Benutzername',
      placeholder: 'Gib deinen Benutzernamen ein',
      hint: '3-20 Zeichen. Nur Buchstaben, Zahlen und Unterstriche.',
      updateButton: 'Aktualisieren',
      validation: {
        lengthError: 'Benutzername muss zwischen 3 und 20 Zeichen lang sein',
        formatError: 'Benutzername darf nur Buchstaben, Zahlen und Unterstriche enthalten',
        alreadyTaken: 'Benutzername bereits vergeben',
      },
    },
    passwordSection: {
      title: 'Passwort',
      description:
        'Ändere dein Passwort. Stelle sicher, dass es mindestens 8 Zeichen lang ist.',
      currentPasswordLabel: 'Passwort',
      currentPasswordPlaceholder: 'Gib dein aktuelles Passwort ein',
      newPasswordLabel: 'Neues Passwort',
      newPasswordPlaceholder: 'Neues Passwort',
      confirmPasswordLabel: 'Bestätigung',
      confirmPasswordPlaceholder: 'Neues Passwort',
      changeButton: 'Passwort ändern',
    },
    deleteSection: {
      title: 'Konto löschen',
      description: 'Unwiderrufliche Aktion. Alle deine Daten werden gelöscht.',
      dialogTitle: 'Dein Konto löschen',
      dialogDescription: 'Unwiderrufliche Aktion. Alle deine Daten werden gelöscht.',
      confirmationLabel: "Gib 'confirmer' ein, um fortzufahren",
      confirmationPlaceholder: 'confirmer',
      deleteButton: 'Konto löschen',
      deleting: 'Löschen...',
      cancel: 'Abbrechen',
    },
    toasts: {
      usernameUpdated: 'Benutzername aktualisiert',
      usernameUpdatedDesc: 'Dein Benutzername wurde erfolgreich aktualisiert.',
      passwordChanged: 'Passwort geändert',
      passwordChangedDesc: 'Dein Passwort wurde erfolgreich geändert.',
      error: 'Fehler',
      passwordMismatch: 'Die neuen Passwörter stimmen nicht überein',
      updateFailed: 'Fehler beim Aktualisieren des Benutzernamens',
      passwordChangeFailed: 'Fehler beim Ändern des Passworts',
      accountDeleted: 'Konto gelöscht',
      accountDeletedDesc: 'Dein Konto wurde erfolgreich gelöscht.',
      accountDeleteFailed: 'Fehler beim Löschen des Kontos',
    },
  },
  userProfile: {
    profile: 'Profil',
    publicWatchlists: 'Öffentliche Listen',
    publicWatchlist: 'Öffentliche Liste',
    watchlists: 'Listen',
    watchlist: 'Liste',
    noPublicWatchlists: 'Keine Listen veröffentlicht.',
    noPublicWatchlistsDescription:
      'Dieser Benutzer hat noch keine öffentlichen Listen veröffentlicht.',
    loading: 'Profil wird geladen...',
    notFound: 'Benutzer nicht gefunden',
    notFoundDescription: 'Der gesuchte Benutzer existiert nicht oder wurde gelöscht.',
    backToHome: 'Zurück zur Startseite',
  },
};
