import type { Content } from '@/types/content';

export const fr: Content = {
  // Header
  header: {
    appName: 'Poplist',
    home: 'Accueil',
    explore: 'Explorer',
    login: 'Connexion',
    signup: 'Inscription',
    logout: 'Déconnexion',
    myLists: 'Mes listes',
    categories: 'Catégories',
  },

  // Auth Drawer
  auth: {
    loginTitle: 'Connexion',
    loginDescription: 'Connecte-toi pour accéder à tes listes.',
    signupTitle: 'Inscription',
    signupDescription: 'Crée un compte pour sauvegarder tes listes.',
    continueWithGoogle: 'Continuer avec Google',
    or: 'Ou',
    email: 'Email',
    emailPlaceholder: 'ton@email.com',
    password: 'Mot de passe',
    passwordPlaceholder: 'Ton mot de passe',
    processing: 'Traitement...',
    dontHaveAccount: "Tu n'as pas de compte ?",
    alreadyHaveAccount: 'Tu as déjà un compte ?',
  },

  // Watchlists Page
  watchlists: {
    title: 'Bibliothèque',
    createWatchlist: 'Nouvelle liste',
    createWatchlistDescription: 'Crée une nouvelle liste pour organiser tes films et séries.',
    noWatchlistsMobile: 'Aucune liste',
    createWatchlistDescriptionMobile: 'Crée ta première liste.',
    noWatchlists: "Tu n'as pas encore créé de liste.",
    signupCta: {
      title: 'Crée un compte',
      description: 'Crée des listes de films et séries, puis partage-les avec la communauté.',
      button: "S'inscrire",
    },
    myWatchlists: 'Mes listes',
    followed: 'Suivies',
    noWatchlistsInCategory: 'Aucune liste dans cette catégorie',
    adjustFilters: 'Ajustez les filtres pour voir plus de listes',
    items: 'éléments',
    item: 'élément',
    by: 'par',
    saveCount: 'sauvegarde',
    savesCount: 'sauvegardes',
    loading: 'Chargement...',
    accountDataBadge: 'Données du compte utilisateur',
    preview: 'Aperçu',
    categories: 'Catégories / Tags',
    categoriesDescription:
      'Sélectionne une ou plusieurs catégories pour faciliter la découverte de ta liste',
    genreCategories: 'Catégories par genre',
    platformCategories: 'Plateformes de streaming',
    platformsDescription: 'Sélectionne les plateformes sur lesquelles ta liste est disponible',
    name: 'Nom',
    namePlaceholder: 'Ma liste',
    description: 'Description',
    descriptionPlaceholder: 'Description de ta liste',
    coverImage: 'Image de couverture',
    uploadImage: 'Télécharger une image',
    changeImage: "Changer l'image",
    imageUploadHint: 'PNG, JPG ou WEBP (max. 5MB)',
    removeImage: 'Supprimer la cover',
    cancel: 'Annuler',
    create: 'Créer',
    creating: 'Création...',
    back: 'Retour',
    noItemsYet: 'Aucun élément pour le moment',
    noItemsDescription:
      'Commence à ajouter des films et séries à ta liste pour organiser ta liste de visionnage.',
    edit: 'Modifier',
    editWatchlist: 'Modifier la liste',
    editWatchlistDescription: 'Modifie les informations de ta liste.',
    deleteWatchlist: 'Supprimer la liste',
    deleteWatchlistConfirm: 'Tu es sûr de vouloir supprimer "{name}" ?',
    deleteWatchlistWarning:
      'Cette liste contient {count} élément(s) qui seront également supprimés.',
    saving: 'Enregistrement...',
    save: 'Enregistrer',
    deleting: 'Suppression...',
    delete: 'Supprimer',
    addItem: 'Ajouter',
    searchMoviesAndSeries: 'Ajouter des éléments à ta liste',
    searchPlaceholder: 'Rechercher un film ou une série...',
    searching: 'Recherche...',
    noResults: 'Aucun résultat trouvé',
    startSearching: 'Recherche des films et séries à ajouter à tes listes.',
    add: 'Ajouter',
    added: 'Ajouté',
    inWatchlist: 'Dans la liste',
    recommendations: {
      title: 'Recommandés',
      similarTitle: 'Contenu similaire',
      subtitle: 'En fonction du contenu de cette liste',
      refresh: 'Actualiser',
    },
    // Table headers
    tableHeaders: {
      number: '#',
      title: 'Titre',
      type: 'Type',
      platforms: 'Plateformes',
      duration: 'Durée',
    },
    // Content types
    contentTypes: {
      movie: 'Film',
      series: 'Série',
    },
    // Series info
    seriesInfo: {
      season: 'saison',
      seasons: 'saisons',
      episodes: 'épisodes',
    },
    // Item Details Modal
    itemDetails: {
      loading: 'Chargement...',
      error: 'Échec du chargement des détails',
      mediaDetails: 'Détails du média',
      fullDetailsFor: 'Détails complets pour',
      loadingDetails: 'Chargement des détails',
      notAvailable: 'N/A',
      votes: 'votes',
      synopsis: 'Synopsis',
      director: 'Réalisateur',
      creator: 'Créateur',
      availableOn: 'Disponible sur',
      availableShort: 'Dispo',
      mainCast: 'Acteurs principaux',
      seeMore: 'Voir plus',
      seeLess: 'Voir moins',
    },
    tooltips: {
      share: 'Partager',
      save: 'Ajouter à la bibliothèque',
      unsave: 'Retirer de la bibliothèque',
      duplicate: 'Dupliquer dans mon espace',
      inviteCollaborator: 'Inviter un collaborateur',
    },
    contextMenu: {
      addToWatchlist: 'Ajouter à une liste',
      removeFromWatchlist: 'Retirer de la liste',
      moveToFirst: 'Déplacer en première position',
      moveToLast: 'Déplacer en dernière position',
    },
    collaborators: {
      addTitle: 'Ajouter un collaborateur',
      addDescription: 'Entre le nom utilisateur du collaborateur',
      usernamePlaceholder: "Nom d'utilisateur",
      add: 'Ajouter',
      adding: 'Ajout...',
      addSuccess: 'Collaborateur ajouté avec succès',
      addError: "Impossible d'ajouter le collaborateur",
      currentTitle: 'Collaborateurs actuels',
      remove: 'Retirer',
      removeSuccess: 'Collaborateur retiré',
      removeError: 'Impossible de retirer le collaborateur',
      leaveTitle: 'Quitter la liste ?',
      leaveDescription:
        'Tu es sûr de vouloir quitter cette liste ? Tu perdras tes droits de collaborateur.',
      leave: 'Quitter',
      leaving: 'Sortie...',
      leaveSuccess: 'Tu as quitté la liste',
      leaveError: 'Échec de la sortie de la liste',
    },
    addToWatchlist: 'Ajouter à une liste',
    noWatchlist: 'Aucune liste',
    toasts: {
      linkCopied: 'Lien copié',
      linkCopyError: 'Impossible de copier le lien',
      listSaved: 'Liste ajoutée',
      listUnsaved: 'Liste retirée',
      listSaveError: 'Impossible de modifier la liste',
      duplicating: 'Duplication en cours...',
      listDuplicated: 'Liste dupliquée',
      duplicateError: 'Impossible de dupliquer la liste',
      itemAdded: 'Ajouté à la liste',
      itemRemoved: 'Retiré de la liste',
      itemAddError: "L'ajout a échoué, réessayez",
      itemRemoveError: 'Le retrait a échoué, réessayez',
    },
  },

  landing: {
    hero: {
      title: 'Crée des listes de tes contenus préférés',
      subtitle: 'Organise tes soirées TV et partage tes découvertes',
      titleMobile: 'Crée des listes de tes contenus favoris',
      subtitleMobile: 'Organise tes soirées TV',
    },
    features: {
      sectionTitle: 'Découvre toutes nos fonctionnalités',
      sectionTitleMobile: 'Nos fonctionnalités',
      sectionSubtitle: 'Partage ton univers cinématographique',
      organize: {
        tagline: 'Organisation',
        title: 'Création de listes',
        description: 'Crée des listes personnelles de films et séries à regarder.',
      },
      collaborate: {
        tagline: 'Collaboration',
        title: 'Ajoute des collaborateurs',
        description: 'Invite tes amis à contribuer à tes listes en temps réel.',
      },
      share: {
        tagline: 'Partage',
        title: 'Partage tes listes',
        description: 'Partage tes listes avec un simple lien pour ton entourage.',
      },
      discover: {
        tagline: 'Découverte',
        title: 'Suis les listes de la communauté',
        description: "Explorez et suivez les listes d'autres utilisateurs.",
      },
    },
    startInSeconds: {
      title: 'Démarrez dans la seconde',
      subtitle: "Pas de set-up compliqué, c'est toi et tes contenus préférés.",
      step1: {
        title: 'Crée ta liste',
        description: 'Donne un nom mémorable à ta nouvelle liste selon son contenu.',
      },
      step2: {
        title: 'Ajoute des films',
        description: 'Ajoute des films et séries de tes plateformes préférées.',
      },
      step3: {
        title: 'Partage ta liste',
        description: 'Copie le lien public de ta liste pour le partager facilement.',
      },
    },
    testimonials: {
      title: 'Apprécié par les passionnés',
      titleMobile: 'Témoignages',
      subtitle: "Rejoignez une communauté d'utilisateurs satisfaits",
      testimonial1: {
        text: 'Application parfaite pour organiser mes listes. Interface claire et intuitive.',
        author: 'Marie C.',
        pseudo: '@mariec',
      },
      testimonial2: {
        text: "Très pratique ! Permet de garder une trace de ce qu'on a vu et de ce qu'on souhaite recommander.",
        author: 'Thomas D.',
        pseudo: '@thomasdlt',
      },
      testimonial3: {
        text: 'Simple, efficace, exactement ce que je cherchais pour gérer mes films à voir.',
        author: 'Julie M.',
        pseudo: '@juliem',
      },
      testimonial4: {
        text: "Le partage par lien, c'est ce qui m'a convaincu. Mes amis voient ma liste sans créer de compte.",
        author: 'Karim B.',
        pseudo: '@karimb',
      },
      testimonial5: {
        text: 'On prépare nos soirées séries à deux, chacun ajoute ses envies dans la même liste.',
        author: 'Léa P.',
        pseudo: '@leapasc',
      },
      testimonial6: {
        text: "Enfin un endroit où je retrouve tout ce qu'on m'a recommandé. Je ne cherche plus pendant 20 minutes.",
        author: 'Antoine R.',
        pseudo: '@antoiner',
      },
    },
    finalCta: {
      title: 'Commence à créer tes listes facilement',
      titleMobile: "Rejoins l'aventure",
      subtitle: 'Rejoins Poplist et organise tes contenus favoris en quelques clics.',
      subtitleMobile: 'Rejoins notre communauté',
      button: 'Créer ma liste',
      disclaimer: 'Application gratuite • Pas de carte bancaire',
    },
  },

  // Home Page
  home: {
    hero: {
      title: 'Tes listes parfaitement organisées',
      subtitle: 'Ton univers cinéma, organisé et partagé avec tes amis.',
      cta: 'Découvrir',
      ctaSecondary: 'En savoir plus',
      pills: {
        organize: 'Organise tes films',
        share: 'Partage avec tes amis',
        discover: 'Découvre des pépites',
      },
    },
    library: {
      title: 'Bibliothèque',
      subtitle: 'Tes listes personnelles',
      seeAll: 'Voir tout',
    },
    categories: {
      title: 'Listes par catégorie',
      subtitle: 'Catégorie Poplist',
      seeMore: 'Voir tout',
      list: 'liste',
      lists: 'listes',
    },
    platformsSection: {
      title: 'Listes par plateformes',
      subtitle: 'Tes plateformes favorites',
      seeAll: 'Voir tout',
    },
    popularWatchlists: {
      title: 'Listes populaires',
      subtitle: 'Partagées par la communauté',
      seeMore: 'Voir tout',
      noWatchlists: 'Aucune liste publique pour le moment',
      loadError: "Les listes n'ont pas pu être chargées",
      retry: 'Réessayer',
    },
    faq: {
      title: 'Questions fréquentes',
      subtitle:
        'Les questions fréquentes sur la plateforme : son fonctionnement, le principe et sa valeur ajoutée.',
      questions: {
        pricing: {
          question: "Est-ce que c'est gratuit ?",
          answer:
            "Oui, l'application est entièrement gratuite ! Tu peux créer autant de listes que tu veux, les partager avec tes amis et explorer des milliers de films et séries sans aucun frais.",
        },
        exploreSection: {
          question: 'À quoi sert la page Explorer ?',
          answer:
            'La section Explorer te permet de découvrir de nouveaux contenus en parcourant les tendances actuelles, les films et séries les plus populaires ou les mieux notés. Tu peux filtrer par genre pour trouver exactement ce que tu recherches et ajouter directement des éléments à tes listes.',
        },
        whatMakesDifferent: {
          question: 'En quoi cette application est différente ?',
          answer:
            "L'expérience est simple avec peu de fonctionnalités, le but c'est de répondre le plus efficacement au besoin. L'expérience se veut naturelle et intuitive, sans complexité inutile.",
        },
        streaming: {
          question: 'Je peux regarder des séries ou des films ?',
          answer: `Poplist n'est pas une plateforme de streaming. L'idée, c'est de garder une trace de ce que tu veux voir et de partager tes coups de cœur. Le visionnage se fait ensuite sur les services de streaming.`,
        },
      },
    },
    trending: {
      title: 'Tendances',
      subtitle: 'Les films et séries du moment',
      noImage: "Pas d'image",
      seeMore: 'Voir tout',
    },
    recommendations: {
      title: 'Tendances du moment',
      subtitle: 'Les titres qui cartonnent cette semaine.',
      seeMore: 'Voir tout',
    },
    creators: {
      title: 'Nos créateurs',
      subtitle: 'Les membres les plus actifs de la communauté',
      seeMore: 'Voir tout',
    },
    communityWatchlists: {
      title: 'Par la communauté',
      subtitle: 'Découvre les collections partagées par nos utilisateurs',
    },
  },

  explore: {
    title: 'Explorer',
    subtitle: 'Découvre de nouvelles listes partagées par la communauté',
    searchPlaceholder: 'Rechercher un film ou une série...',
    filters: {
      all: 'Tout',
      movies: 'Films',
      series: 'Séries',
      trending: 'Tendances',
      topRated: 'Mieux notés',
      popular: 'Populaires',
      bestRated: 'Mieux notés',
      yearMin: 'Année minimum',
      yearMax: 'Année maximum',
      search: 'Rechercher...',
      noYearFound: 'Aucune année trouvée.',
      clearYears: 'Effacer les années',
      genres: 'Genres',
      year: 'Année',
      apply: 'Appliquer',
    },
    genres: {
      action: 'Action',
      adventure: 'Aventure',
      animation: 'Animation',
      comedy: 'Comédie',
      crime: 'Crime',
      documentary: 'Documentaire',
      drama: 'Drame',
      family: 'Familial',
      fantasy: 'Fantastique',
      horror: 'Horreur',
      romance: 'Romance',
      scienceFiction: 'Science-Fiction',
      thriller: 'Thriller',
      actionAdventure: 'Action & Aventure',
      kids: 'Enfants',
      mystery: 'Mystère',
      sciFiFantasy: 'Science-Fiction & Fantastique',
      soap: 'Feuilleton',
      western: 'Western',
    },
    sortBy: {
      label: 'Trier par',
      popular: 'Les plus populaires',
      recentlyAdded: 'Récemment ajoutées',
      mostItems: "Plus d'éléments",
    },
    pagination: {
      pageOf: 'Page {page} sur {totalPages}',
    },
    noResults: 'Aucune liste trouvée',
    noResultsDescription: 'Essaie de modifier tes filtres ou ta recherche',
  },

  categories: {
    title: 'Catégories',
    subtitle: 'Explore les listes par thème',
    list: {
      movies: {
        name: 'Films',
        description: 'Les films à ne pas manquer',
      },
      series: {
        name: 'Séries',
        description: 'Les séries à ne pas manquer',
      },
      animation: {
        name: 'Animation',
        description: "Les meilleurs séries et films d'animation",
      },
      enfant: {
        name: 'Enfant',
        description: 'Films et séries pour enfant',
      },
      jeunesse: {
        name: 'Jeunesse',
        description: 'Films et séries adolescent et adulte',
      },
      documentaries: {
        name: 'Documentaires',
        nameMobile: 'Docu',
        description: 'Documentaires captivants et éducatifs',
      },
      action: {
        name: 'Action',
        description: "Classiques et nouveautés films d'actions",
      },
      anime: {
        name: 'Anime',
        description: 'Animes japonais et mangas adaptés',
      },
    },
  },

  // Footer
  footer: {
    appName: 'Poplist',
    language: 'Langue',
  },

  // Profile Page
  profile: {
    title: 'Paramètres du profil',
    subtitle: 'Gère les paramètres et préférences de ton compte',
    userInformation: 'Informations utilisateur',
    avatarSection: {
      title: 'Photo de profil',
      description: 'Télécharge une photo de profil pour personnaliser ton compte',
      uploadButton: 'Télécharger',
      changeButton: 'Modifier',
      deleteButton: 'Supprimer',
      uploading: 'Téléchargement...',
      deleting: 'Suppression...',
      hint: 'Recommandé : Image carrée, 5 Mo maximum',
      validation: {
        invalidFileType: 'Veuillez sélectionner un fichier image valide',
        fileTooLarge: "La taille de l'image doit être inférieure à 5 Mo",
        uploadFailed: "Échec du téléchargement de l'avatar",
        deleteFailed: "Échec de la suppression de l'avatar",
        readFailed: 'Échec de la lecture du fichier image',
      },
      toasts: {
        updated: 'Avatar mis à jour',
        updatedDesc: 'Ton avatar a été mis à jour avec succès',
        deleted: 'Avatar supprimé',
        deletedDesc: 'Ton avatar a été supprimé avec succès',
      },
    },
    usernameSection: {
      title: "Nom d'utilisateur",
      description: "Modifie ton nom d'utilisateur. C'est ainsi que les autres te verront.",
      label: "Nom d'utilisateur",
      placeholder: "Entre ton nom d'utilisateur",
      hint: '3-20 caractères. Lettres, chiffres et underscores uniquement.',
      updateButton: 'Mettre à jour',
      validation: {
        lengthError: "Le nom d'utilisateur doit contenir entre 3 et 20 caractères",
        formatError:
          "Le nom d'utilisateur ne peut contenir que des lettres, chiffres et underscores",
        alreadyTaken: "Le nom d'utilisateur est déjà pris",
      },
    },
    passwordSection: {
      title: 'Mot de passe',
      description: "Change ton mot de passe. Assure-toi qu'il contient au moins 8 caractères.",
      currentPasswordLabel: 'Mot de passe',
      currentPasswordPlaceholder: 'Entre ton mot de passe actuel',
      newPasswordLabel: 'Nouveau mot de passe',
      newPasswordPlaceholder: 'Nouveau mot de passe',
      confirmPasswordLabel: 'Confirmation',
      confirmPasswordPlaceholder: 'Nouveau mot de passe',
      changeButton: 'Changer le mot de passe',
    },
    deleteSection: {
      title: 'Supprimer le compte',
      description: 'Action irréversible. Toutes tes données seront supprimées.',
      dialogTitle: 'Supprimer ton compte',
      dialogDescription: 'Action irréversible. Toutes tes données seront supprimées.',
      confirmationLabel: "Tapez 'confirmer' pour continuer",
      confirmationPlaceholder: 'confirmer',
      deleteButton: 'Supprimer le compte',
      deleting: 'Suppression...',
      cancel: 'Annuler',
    },
    toasts: {
      usernameUpdated: "Nom d'utilisateur mis à jour",
      usernameUpdatedDesc: "Ton nom d'utilisateur a été mis à jour avec succès.",
      passwordChanged: 'Mot de passe changé',
      passwordChangedDesc: 'Ton mot de passe a été changé avec succès.',
      accountDeleted: 'Compte supprimé',
      accountDeletedDesc: 'Ton compte a été supprimé avec succès.',
      error: 'Erreur',
      passwordMismatch: 'Les nouveaux mots de passe ne correspondent pas',
      updateFailed: "Échec de la mise à jour du nom d'utilisateur",
      passwordChangeFailed: 'Échec du changement de mot de passe',
      accountDeleteFailed: 'Échec de la suppression du compte',
    },
  },
  userProfile: {
    profile: 'Profil',
    publicWatchlists: 'Listes publiques',
    publicWatchlist: 'Liste publique',
    watchlists: 'listes',
    watchlist: 'liste',
    noPublicWatchlists: "Aucune liste n'a été publiée.",
    noPublicWatchlistsDescription: "Cet utilisateur n'a pas encore publié de liste publique.",
    loading: 'Chargement du profil...',
    notFound: 'Utilisateur introuvable',
    notFoundDescription: "L'utilisateur que tu recherches n'existe pas ou a été supprimé.",
    backToHome: "Retour à l'accueil",
  },
};
