import type { Content } from '@/types/content';

export const pt: Content = {
  // Header
  header: {
    appName: 'Poplist',
    home: 'Início',
    explore: 'Explorar',
    login: 'Entrar',
    signup: 'Registar',
    logout: 'Sair',
    myLists: 'Minhas listas',
    categories: 'Categorias',
  },

  // Auth Drawer
  auth: {
    loginTitle: 'Entrar',
    loginDescription: 'Bem-vindo de volta! Inicia sessão para acederes às tuas listas.',
    signupTitle: 'Registar',
    signupDescription: 'Cria uma conta para guardares as tuas listas.',
    continueWithGoogle: 'Continuar com Google',
    or: 'Ou',
    email: 'Email',
    emailPlaceholder: 'seu@email.pt',
    password: 'Palavra-passe',
    passwordPlaceholder: 'A sua palavra-passe',
    processing: 'A processar...',
    dontHaveAccount: 'Não tem uma conta?',
    alreadyHaveAccount: 'Já tem uma conta?',
  },

  // Watchlists Page
  watchlists: {
    title: 'Biblioteca',
    createWatchlist: 'Nova lista',
    createWatchlistDescription: 'Cria uma nova lista para organizares os teus filmes e séries.',
    noWatchlistsMobile: 'Nenhuma lista',
    createWatchlistDescriptionMobile: 'Cria a tua primeira lista.',
    noWatchlists: 'Ainda não criou nenhuma lista.',
    signupCta: {
      title: 'Cria uma conta',
      description: 'Cria listas de filmes e séries e partilha-as com a comunidade.',
      button: 'Cadastre-se',
    },
    myWatchlists: 'As minhas listas',
    followed: 'Seguidas',
    noWatchlistsInCategory: 'Nenhuma lista nesta categoria',
    adjustFilters: 'Ajuste os filtros para ver mais listas',
    items: 'itens',
    item: 'item',
    by: 'por',
    saveCount: 'guardado',
    savesCount: 'guardados',
    loading: 'A carregar...',
    accountDataBadge: 'Dados da conta de utilizador',
    preview: 'Pré-visualização',
    categories: 'Categorias / Etiquetas',
    categoriesDescription:
      'Seleciona uma ou mais categorias para facilitar a descoberta da tua lista',
    genreCategories: 'Categorias de género',
    platformCategories: 'Plataformas de streaming',
    platformsDescription: 'Seleciona as plataformas onde a tua lista está disponível',
    name: 'Nome',
    namePlaceholder: 'A minha lista',
    description: 'Descrição',
    descriptionPlaceholder: 'Descrição da sua lista',
    coverImage: 'Imagem de capa',
    uploadImage: 'Carregar imagem',
    changeImage: 'Alterar imagem',
    imageUploadHint: 'PNG, JPG ou WEBP (máx. 5MB)',
    removeImage: 'Remover a capa',
    cancel: 'Cancelar',
    create: 'Criar',
    creating: 'A criar...',
    back: 'Voltar',
    noItemsYet: 'Ainda sem itens',
    noItemsDescription:
      'Começa a adicionar filmes e séries à tua lista para organizares a tua fila de visualização.',
    edit: 'Editar',
    editWatchlist: 'Editar lista',
    editWatchlistDescription: 'Edite as informações da sua lista.',
    deleteWatchlist: 'Eliminar lista',
    deleteWatchlistConfirm:
      'Tem a certeza de que deseja eliminar "{name}"? Esta ação é irreversível.',
    deleteWatchlistWarning: 'Esta lista contém {count} item(ns) que também serão eliminados.',
    saving: 'A guardar...',
    save: 'Guardar',
    deleting: 'A eliminar...',
    delete: 'Eliminar',
    addItem: 'Adicionar',
    searchMoviesAndSeries: 'Pesquise e adicione filmes ou séries à sua lista',
    searchPlaceholder: 'Pesquisar um filme ou série...',
    searching: 'A pesquisar...',
    noResults: 'Nenhum resultado encontrado',
    startSearching: 'Começa a escrever para pesquisar filmes e séries',
    add: 'Adicionar',
    added: 'Adicionado',
    inWatchlist: 'Na lista',
    recommendations: {
      title: 'Recomendados',
      similarTitle: 'Conteúdo semelhante',
      subtitle: 'Com base no conteúdo desta lista',
      refresh: 'Atualizar',
    },
    // Table headers
    tableHeaders: {
      number: '#',
      title: 'Título',
      type: 'Tipo',
      platforms: 'Plataformas',
      duration: 'Duração',
    },
    // Content types
    contentTypes: {
      movie: 'Filme',
      series: 'Série',
    },
    // Series info
    seriesInfo: {
      season: 'temporada',
      seasons: 'temporadas',
      episodes: 'episódios',
    },
    // Item Details Modal
    itemDetails: {
      loading: 'A carregar...',
      error: 'Falha ao carregar os detalhes',
      mediaDetails: 'Detalhes do conteúdo',
      fullDetailsFor: 'Detalhes completos de',
      loadingDetails: 'A carregar detalhes',
      notAvailable: 'N/D',
      votes: 'votos',
      synopsis: 'Sinopse',
      director: 'Realizador',
      creator: 'Criador',
      availableOn: 'Disponível em',
      availableShort: 'Disponível',
      mainCast: 'Elenco principal',
      seeMore: 'Ver mais',
      seeLess: 'Ver menos',
    },
    tooltips: {
      share: 'Partilhar',
      save: 'Adicionar à biblioteca',
      unsave: 'Remover da biblioteca',
      duplicate: 'Duplicar no meu espaço',
      inviteCollaborator: 'Convidar um colaborador',
    },
    contextMenu: {
      addToWatchlist: 'Adicionar à lista',
      removeFromWatchlist: 'Remover da lista',
      moveToFirst: 'Mover para primeira posição',
      moveToLast: 'Mover para última posição',
    },
    collaborators: {
      addTitle: 'Adicionar Colaborador',
      addDescription: 'Digite o nome de usuário do colaborador',
      usernamePlaceholder: 'Nome de usuário',
      add: 'Adicionar',
      adding: 'Adicionando...',
      addSuccess: 'Colaborador adicionado com sucesso',
      addError: 'Falha ao adicionar colaborador',
      currentTitle: 'Colaboradores Atuais',
      remove: 'Remover',
      removeSuccess: 'Colaborador removido',
      removeError: 'Falha ao remover colaborador',
      leaveTitle: 'Sair da lista?',
      leaveDescription:
        'Tens a certeza de que queres sair desta lista? Vais perder os teus direitos de colaborador.',
      leave: 'Sair',
      leaving: 'Saindo...',
      leaveSuccess: 'Você saiu da lista',
      leaveError: 'Falha ao sair da lista',
    },
    addToWatchlist: 'Adicionar a uma lista',
    noWatchlist: 'Nenhuma lista',
    toasts: {
      linkCopied: 'Link copiado',
      linkCopyError: 'Não foi possível copiar o link',
      listSaved: 'Lista adicionada',
      listUnsaved: 'Lista removida',
      listSaveError: 'Não foi possível atualizar a lista',
      duplicating: 'Duplicando...',
      listDuplicated: 'Lista duplicada',
      duplicateError: 'Não foi possível duplicar a lista',
      itemAdded: 'Adicionado à lista',
      itemRemoved: 'Removido da lista',
      itemAddError: 'Não foi possível adicionar, tenta de novo',
      itemRemoveError: 'Não foi possível remover, tenta de novo',
    },
  },

  landing: {
    hero: {
      title: 'Cria e partilha listas dos teus conteúdos favoritos',
      subtitle: 'Organiza as tuas noites de TV e partilha as tuas descobertas com os teus amigos',
      titleMobile: 'Cria listas dos teus conteúdos favoritos',
      subtitleMobile: 'Organiza as tuas noites de TV',
    },
    features: {
      sectionTitle: 'Compartilhe seu universo cinematográfico',
      sectionTitleMobile: 'Nossas funcionalidades',
      sectionSubtitle: 'Descubra todas as nossas funcionalidades',
      organize: {
        tagline: 'Organização',
        title: 'Cria listas',
        description: 'Cria listas pessoais de filmes e séries para veres.',
      },
      collaborate: {
        tagline: 'Colaboração',
        title: 'Adicione colaboradores',
        description: 'Convida amigos para contribuírem para as tuas listas em tempo real.',
      },
      share: {
        tagline: 'Compartilhamento',
        title: 'Partilha as tuas listas',
        description: 'Partilha as tuas listas com um simples link para os teus amigos.',
      },
      discover: {
        tagline: 'Descoberta',
        title: 'Siga as listas da comunidade',
        description: 'Explore e siga as listas de outros usuários.',
      },
    },
    startInSeconds: {
      title: 'Começa em segundos',
      subtitle: 'Sem configuração complicada, apenas tu e o teu conteúdo favorito',
      step1: {
        title: 'Cria a tua lista',
        description: 'Dê um nome à sua lista e comece a organizar.',
      },
      step2: {
        title: 'Adicione filmes',
        description: 'Adicione filmes e séries em poucos cliques.',
      },
      step3: {
        title: 'Partilha com os teus amigos',
        description: 'Um link é tudo o que precisas para partilhar.',
      },
    },
    testimonials: {
      title: 'Amado pelos entusiastas',
      titleMobile: 'Depoimentos',
      subtitle: 'Junte-se a uma comunidade de usuários satisfeitos',
      testimonial1: {
        text: 'Aplicativo perfeito para organizar minhas listas. Interface clara e intuitiva.',
        author: 'Marie L.',
        pseudo: '@maried',
      },
      testimonial2: {
        text: 'Muito prático! Ajuda a manter o controle do que assistimos e do que queremos recomendar.',
        author: 'Thomas D.',
        pseudo: '@thomasdlm',
      },
      testimonial3: {
        text: 'Simples, eficaz, exatamente o que eu procurava para gerenciar meus filmes para assistir.',
        author: 'Julie M.',
        pseudo: '@juliem',
      },
      testimonial4: {
        text: 'Compartilhar com um link foi o que me convenceu. Meus amigos veem minha lista sem criar conta.',
        author: 'Karim B.',
        pseudo: '@karimb',
      },
      testimonial5: {
        text: 'Planejamos nossas noites de séries juntos, cada um adiciona à mesma lista.',
        author: 'Léa P.',
        pseudo: '@leapasc',
      },
      testimonial6: {
        text: 'Finalmente um lugar com tudo que me recomendam. Chega de procurar por 20 minutos.',
        author: 'Antoine R.',
        pseudo: '@antoiner',
      },
    },
    finalCta: {
      title: 'Começa a criar as tuas listas facilmente',
      titleMobile: 'Junte-se à aventura',
      subtitle: 'Junta-te ao Poplist e organiza os teus conteúdos favoritos em poucos cliques.',
      subtitleMobile: 'Junte-se à nossa comunidade',
      button: 'Criar minha lista',
      disclaimer: 'Aplicativo gratuito • Não é necessário cartão',
    },
  },

  // Home Page
  home: {
    hero: {
      title: 'Suas listas perfeitamente organizadas',
      subtitle: 'O seu universo cinematográfico, organizado e partilhado com amigos.',
      cta: 'Descobrir',
      ctaSecondary: 'Saber mais',
      pills: {
        organize: 'Organiza os teus filmes',
        share: 'Partilha com os teus amigos',
        discover: 'Descubra pérolas',
      },
    },
    library: {
      title: 'Biblioteca',
      subtitle: 'Suas listas pessoais',
      seeAll: 'Ver tudo',
    },
    categories: {
      title: 'Listas por categoria',
      subtitle: 'Seleção Poplist',
      seeMore: 'Ver mais',
      list: 'lista',
      lists: 'listas',
    },
    platformsSection: {
      title: 'Listas por plataforma',
      subtitle: 'As tuas plataformas favoritas',
      seeAll: 'Ver tudo',
    },
    popularWatchlists: {
      title: 'Listas populares',
      subtitle: 'Partilhadas pela comunidade',
      seeMore: 'Ver mais',
      noWatchlists: 'Nenhuma lista pública no momento',
      loadError: 'Não foi possível carregar as listas',
      retry: 'Tentar de novo',
    },
    faq: {
      title: 'Perguntas frequentes',
      subtitle: 'As perguntas mais frequentes sobre a plataforma: o princípio, o nosso valor acrescentado e como funciona.',
      questions: {
        pricing: {
          question: 'É gratuito para usar?',
          answer:
            'Sim, a aplicação é completamente gratuita! Podes criar tantas listas quantas quiseres, partilhá-las com os teus amigos e explorar milhares de filmes e séries sem qualquer custo.',
        },
        exploreSection: {
          question: 'Para que serve a secção Explorar?',
          answer:
            'A secção Explorar permite-te descobrir novos conteúdos navegando pelas tendências atuais, os filmes e séries mais populares ou mais bem classificados. Podes filtrar por género para encontrares exatamente o que procuras e adicionar elementos diretamente às tuas listas.',
        },
        whatMakesDifferent: {
          question: 'O que torna esta aplicação diferente?',
          answer:
            'Esta aplicação visa manter-se simples com poucas funcionalidades e páginas para ser clara e fácil de usar. A experiência pretende ser natural e intuitiva, sem complexidade desnecessária. Focamo-nos no essencial: organizar e partilhar os teus filmes e séries favoritos.',
        },
        streaming: {
          question: 'Posso ver séries ou filmes?',
          answer:
            'Não, o objetivo desta aplicação não é o streaming mas a partilha fácil de conteúdos de que gostaste nas tuas plataformas favoritas. Ajudamos-te a organizar o que queres ver e a partilhá-lo com a tua comunidade, mas para visualizares o conteúdo, tens de ir às plataformas de streaming apropriadas.',
        },
      },
    },
    trending: {
      title: 'Tendências de hoje',
      subtitle: 'Filmes e séries do momento',
      noImage: 'Sem imagem',
      seeMore: 'Ver tudo',
    },
    recommendations: {
      title: 'Tendências do momento',
      subtitle: 'Os títulos em alta esta semana.',
      seeMore: 'Ver tudo',
    },
    creators: {
      title: 'Nossos criadores',
      subtitle: 'Os membros mais ativos da comunidade',
      seeMore: 'Ver tudo',
    },
    communityWatchlists: {
      title: 'Listas da comunidade',
      subtitle: 'Descubra coleções compartilhadas por nossos usuários',
    },
  },

  explore: {
    title: 'Explorar',
    subtitle: 'Descubra novas listas partilhadas pela comunidade',
    searchPlaceholder: 'Pesquisar um filme ou uma série...',
    filters: {
      all: 'Todas',
      movies: 'Filmes',
      series: 'Séries',
      trending: 'Tendências',
      topRated: 'Mais votados',
      popular: 'Populares',
      bestRated: 'Mais votados',
      yearMin: 'Ano mínimo',
      yearMax: 'Ano máximo',
      search: 'Pesquisar...',
      noYearFound: 'Nenhum ano encontrado.',
      clearYears: 'Limpar anos',
      genres: 'Gêneros',
      year: 'Ano',
      apply: 'Aplicar',
    },
    genres: {
      action: 'Ação',
      adventure: 'Aventura',
      animation: 'Animação',
      comedy: 'Comédia',
      crime: 'Crime',
      documentary: 'Documentário',
      drama: 'Drama',
      family: 'Família',
      fantasy: 'Fantasia',
      horror: 'Terror',
      romance: 'Romance',
      scienceFiction: 'Ficção Científica',
      thriller: 'Thriller',
      actionAdventure: 'Ação e Aventura',
      kids: 'Crianças',
      mystery: 'Mistério',
      sciFiFantasy: 'Ficção Científica e Fantasia',
      soap: 'Novela',
      western: 'Western',
    },
    sortBy: {
      label: 'Ordenar por',
      popular: 'Mais populares',
      recentlyAdded: 'Adicionadas recentemente',
      mostItems: 'Mais itens',
    },
    pagination: {
      pageOf: 'Página {page} de {totalPages}',
    },
    noResults: 'Nenhuma lista encontrada',
    noResultsDescription: 'Tenta ajustar os teus filtros ou a pesquisa',
  },

  categories: {
    title: 'Categorias',
    subtitle: 'Explore listas por tema',
    list: {
      movies: { name: 'Filmes', description: 'Os melhores filmes do momento' },
      series: { name: 'Séries', description: 'Séries imperdíveis' },
      animation: {
        name: 'Animação',
        description: 'As melhores séries e filmes de animação',
      },
      enfant: {
        name: 'Infantil',
        description: 'Filmes e séries para crianças',
      },
      jeunesse: {
        name: 'Jovens',
        description: 'Filmes e séries para adolescentes e jovens adultos',
      },
      documentaries: {
        name: 'Documentários',
        description: 'Documentários cativantes e educativos',
      },
      action: { name: 'Ação', description: 'Clássicos e novos filmes de ação' },
      anime: {
        name: 'Anime',
        description: 'Anime japonês e mangá adaptado',
      },
    },
  },

  // Footer
  footer: {
    appName: 'Poplist',
    language: 'Idioma',
  },

  // Profile Page
  profile: {
    title: 'Definições do perfil',
    subtitle: 'Gerir as definições e preferências da sua conta',
    userInformation: 'Informações do utilizador',
    avatarSection: {
      title: 'Foto de perfil',
      description: 'Carregue uma foto de perfil para personalizar sua conta',
      uploadButton: 'Carregar',
      changeButton: 'Alterar',
      deleteButton: 'Excluir',
      uploading: 'Carregando...',
      deleting: 'Excluindo...',
      hint: 'Recomendado: Imagem quadrada, máx. 5MB',
      validation: {
        invalidFileType: 'Por favor, selecione um arquivo de imagem válido',
        fileTooLarge: 'O tamanho da imagem deve ser inferior a 5MB',
        uploadFailed: 'Falha ao carregar o avatar',
        deleteFailed: 'Falha ao excluir o avatar',
        readFailed: 'Falha ao ler o arquivo de imagem',
      },
      toasts: {
        updated: 'Avatar atualizado',
        updatedDesc: 'O teu avatar foi atualizado com sucesso',
        deleted: 'Avatar excluído',
        deletedDesc: 'O teu avatar foi eliminado com sucesso',
      },
    },
    usernameSection: {
      title: 'Nome de utilizador',
      description: 'Atualiza o teu nome de utilizador. É assim que os outros te verão.',
      label: 'Nome de utilizador',
      placeholder: 'Introduz o teu nome de utilizador',
      hint: '3-20 caracteres. Apenas letras, números e sublinhados.',
      updateButton: 'Atualizar',
      validation: {
        lengthError: 'O nome de utilizador deve ter entre 3 e 20 caracteres',
        formatError: 'O nome de utilizador só pode conter letras, números e sublinhados',
        alreadyTaken: 'Nome de utilizador já em uso',
      },
    },
    passwordSection: {
      title: 'Palavra-passe',
      description: 'Altera a tua palavra-passe. Certifica-te de que tem pelo menos 8 caracteres.',
      currentPasswordLabel: 'Palavra-passe',
      currentPasswordPlaceholder: 'Introduz a tua palavra-passe atual',
      newPasswordLabel: 'Nova palavra-passe',
      newPasswordPlaceholder: 'Nova palavra-passe',
      confirmPasswordLabel: 'Confirmação',
      confirmPasswordPlaceholder: 'Nova palavra-passe',
      changeButton: 'Alterar palavra-passe',
    },
    deleteSection: {
      title: 'Eliminar conta',
      description: 'Ação irreversível. Todos os teus dados serão eliminados.',
      dialogTitle: 'Eliminar a tua conta',
      dialogDescription: 'Ação irreversível. Todos os teus dados serão eliminados.',
      confirmationLabel: "Digite 'confirmar' para continuar",
      confirmationPlaceholder: 'confirmar',
      deleteButton: 'Eliminar conta',
      deleting: 'A eliminar...',
      cancel: 'Cancelar',
    },
    toasts: {
      usernameUpdated: 'Nome de utilizador atualizado',
      usernameUpdatedDesc: 'O seu nome de utilizador foi atualizado com sucesso.',
      passwordChanged: 'Palavra-passe alterada',
      passwordChangedDesc: 'A sua palavra-passe foi alterada com sucesso.',
      error: 'Erro',
      passwordMismatch: 'As novas palavras-passe não correspondem',
      updateFailed: 'Falha ao atualizar o nome de utilizador',
      passwordChangeFailed: 'Falha ao alterar a palavra-passe',
      accountDeleted: 'Conta eliminada',
      accountDeletedDesc: 'A sua conta foi eliminada com sucesso.',
      accountDeleteFailed: 'Falha ao eliminar a conta',
    },
  },
  userProfile: {
    profile: 'Perfil',
    publicWatchlists: 'Listas públicas',
    publicWatchlist: 'Lista pública',
    watchlists: 'listas',
    watchlist: 'lista',
    noPublicWatchlists: 'Nenhuma lista publicada.',
    noPublicWatchlistsDescription: 'Este utilizador ainda não publicou nenhuma lista pública.',
    loading: 'A carregar perfil...',
    notFound: 'Utilizador não encontrado',
    notFoundDescription: 'O utilizador que procura não existe ou foi eliminado.',
    backToHome: 'Voltar ao início',
  },
};
