import type { PrivacyContent } from '../../../types/privacy';

export const privacyDe: PrivacyContent = {
  title: 'Datenschutzrichtlinie',
  effective: 'Gültig ab: 22. März 2026',
  intro: 'Diese Datenschutzrichtlinie gilt für Poplist, eine mobile und Web-Anwendung, die von Samuel Prigent erstellt wurde. Poplist ist ein kostenloser Dienst, mit dem Sie Film- und Serienlisten erstellen und teilen können.',
  collectTitle: 'Welche Daten wir erheben',
  collectIntro: 'Wir erheben nur die für den Betrieb der Anwendung notwendigen Daten:',
  collectEmail: 'E-Mail-Adresse (für Kontoerstellung und Authentifizierung)',
  collectUsername: 'Benutzername (von Ihnen gewählt, öffentlich angezeigt)',
  collectAvatar: 'Profilbild (optional, von Ihnen hochgeladen)',
  collectLists: 'Ihre Listen und deren Inhalt (Filme und Serien, die Sie hinzufügen)',
  collectNoTracking: 'Wir verwenden keine Tracking-Cookies. Wir verwenden keinen Analysedienst. Wir erfassen nicht Ihren Standort, Ihre Kontakte oder andere Daten als die oben aufgeführten.',
  useTitle: 'Verwendung Ihrer Daten',
  useDescription: 'Ihre Daten werden ausschließlich zur Bereitstellung des Poplist-Dienstes verwendet: Authentifizierung Ihres Kontos, Anzeige Ihrer Listen und Ermöglichung von Zusammenarbeitsfunktionen. Wir verkaufen, teilen oder übermitteln Ihre Daten nicht an Dritte zu Werbe- oder Analysezwecken.',
  thirdPartyTitle: 'Drittanbieterdienste',
  thirdPartyIntro: 'Die Anwendung nutzt folgende Drittanbieterdienste:',
  thirdPartyExpo: 'Expo — Framework der mobilen App und Update-Bereitstellung',
  thirdPartyGoogle: 'Google OAuth — Authentifizierung (wir erhalten nur Ihre E-Mail, keine anderen Google-Daten)',
  thirdPartyCloudinary: 'Cloudinary — Bildhosting für Profilbilder und Listencover',
  thirdPartyTMDB: 'TMDB — Film- und Serienmetadaten (keine Benutzerdaten werden mit TMDB geteilt)',
  storageTitle: 'Datenspeicherung und Sicherheit',
  storageDescription: 'Ihre Daten werden in einer sicheren Datenbank gespeichert. Die gesamte Kommunikation zwischen der App und unseren Servern ist über HTTPS verschlüsselt. Authentifizierungstoken werden sicher auf Ihrem Gerät gespeichert.',
  deletionTitle: 'Datenlöschung',
  deletionDescription: 'Sie können Ihr Konto jederzeit in den App-Einstellungen löschen. Dadurch werden alle Ihre Daten einschließlich Ihres Profils, Ihrer Listen und zugehörigen Inhalte dauerhaft gelöscht. Sie können die Datenlöschung auch beantragen, indem Sie uns kontaktieren unter',
  childrenTitle: 'Kinder',
  childrenDescription: 'Poplist richtet sich nicht an Kinder unter 13 Jahren. Wir erfassen wissentlich keine persönlichen Daten von Kindern unter 13 Jahren.',
  changesTitle: 'Änderungen',
  changesDescription: 'Diese Datenschutzrichtlinie kann von Zeit zu Zeit aktualisiert werden. Änderungen werden auf dieser Seite wiedergegeben.',
  contactTitle: 'Kontakt',
  contactDescription: 'Bei Fragen zu dieser Richtlinie kontaktieren Sie',
};
