import type { PrivacyContent } from '../../../types/privacy';

export const privacyEn: PrivacyContent = {
  title: 'Privacy Policy',
  effective: 'Effective: March 22, 2026',
  intro: 'This privacy policy applies to Poplist, a mobile and web application created by Samuel Prigent. Poplist is a free service that lets you create and share movie and TV show lists.',
  collectTitle: 'What We Collect',
  collectIntro: 'We only collect the data necessary for the application to function:',
  collectEmail: 'Email address (for account creation and authentication)',
  collectUsername: 'Username (chosen by you, displayed publicly)',
  collectAvatar: 'Profile picture (optional, uploaded by you)',
  collectLists: 'Your lists and their content (movies, TV shows you add)',
  collectNoTracking: 'We do not use cookies for tracking. We do not use any analytics service. We do not collect your location, contacts, or any data beyond what is listed above.',
  useTitle: 'How We Use Your Data',
  useDescription: 'Your data is used exclusively to provide the Poplist service: authenticating your account, displaying your lists, and enabling collaboration features. We do not sell, share, or transmit your data to any third party for advertising or analytics purposes.',
  thirdPartyTitle: 'Third Party Services',
  thirdPartyIntro: 'The application uses the following third-party services:',
  thirdPartyExpo: 'Expo — mobile app framework and update delivery',
  thirdPartyGoogle: 'Google OAuth — authentication (we only receive your email, no other Google data)',
  thirdPartyCloudinary: 'Cloudinary — image hosting for profile pictures and list covers',
  thirdPartyTMDB: 'TMDB — movie and TV show metadata (no user data is shared with TMDB)',
  storageTitle: 'Data Storage and Security',
  storageDescription: 'Your data is stored in a secure database. All communications between the app and our servers are encrypted via HTTPS. Authentication tokens are stored securely on your device.',
  deletionTitle: 'Data Deletion',
  deletionDescription: 'You can delete your account at any time from the app settings. This permanently removes all your data including your profile, lists, and associated content. You can also request data deletion by contacting',
  childrenTitle: 'Children',
  childrenDescription: 'Poplist is not directed at children under 13. We do not knowingly collect personal information from children under 13.',
  changesTitle: 'Changes',
  changesDescription: 'This Privacy Policy may be updated from time to time. Changes will be reflected on this page.',
  contactTitle: 'Contact',
  contactDescription: 'For any questions regarding this policy, contact',
};
