import type { PrivacyContent } from '../../../types/privacy';

export const privacyEs: PrivacyContent = {
  title: 'Política de Privacidad',
  effective: 'Vigente desde: 22 de marzo de 2026',
  intro: 'Esta política de privacidad se aplica a Poplist, una aplicación móvil y web creada por Samuel Prigent. Poplist es un servicio gratuito que permite crear y compartir listas de películas y series.',
  collectTitle: 'Datos que recopilamos',
  collectIntro: 'Solo recopilamos los datos necesarios para el funcionamiento de la aplicación:',
  collectEmail: 'Dirección de correo electrónico (para la creación de cuenta y autenticación)',
  collectUsername: 'Nombre de usuario (elegido por usted, mostrado públicamente)',
  collectAvatar: 'Foto de perfil (opcional, subida por usted)',
  collectLists: 'Sus listas y su contenido (películas y series que añade)',
  collectNoTracking: 'No utilizamos cookies de seguimiento. No utilizamos ningún servicio de análisis. No recopilamos su ubicación, contactos ni ningún dato más allá de lo indicado anteriormente.',
  useTitle: 'Uso de sus datos',
  useDescription: 'Sus datos se utilizan exclusivamente para proporcionar el servicio Poplist: autenticar su cuenta, mostrar sus listas y permitir las funciones de colaboración. No vendemos, compartimos ni transmitimos sus datos a terceros con fines publicitarios o de análisis.',
  thirdPartyTitle: 'Servicios de terceros',
  thirdPartyIntro: 'La aplicación utiliza los siguientes servicios de terceros:',
  thirdPartyExpo: 'Expo — framework de la aplicación móvil y entrega de actualizaciones',
  thirdPartyGoogle: 'Google OAuth — autenticación (solo recibimos su correo electrónico, ningún otro dato de Google)',
  thirdPartyCloudinary: 'Cloudinary — alojamiento de imágenes para fotos de perfil y portadas de listas',
  thirdPartyTMDB: 'TMDB — metadatos de películas y series (no se comparten datos de usuario con TMDB)',
  storageTitle: 'Almacenamiento y seguridad',
  storageDescription: 'Sus datos se almacenan en una base de datos segura. Todas las comunicaciones entre la aplicación y nuestros servidores están cifradas mediante HTTPS. Los tokens de autenticación se almacenan de forma segura en su dispositivo.',
  deletionTitle: 'Eliminación de datos',
  deletionDescription: 'Puede eliminar su cuenta en cualquier momento desde los ajustes de la aplicación. Esto elimina permanentemente todos sus datos, incluyendo su perfil, listas y contenido asociado. También puede solicitar la eliminación de sus datos contactando a',
  childrenTitle: 'Menores',
  childrenDescription: 'Poplist no está dirigido a menores de 13 años. No recopilamos conscientemente información personal de menores de 13 años.',
  changesTitle: 'Cambios',
  changesDescription: 'Esta Política de Privacidad puede actualizarse de vez en cuando. Los cambios se reflejarán en esta página.',
  contactTitle: 'Contacto',
  contactDescription: 'Para cualquier pregunta sobre esta política, contacte a',
};
