import type { PrivacyContent } from '../../../types/privacy';

export const privacyFr: PrivacyContent = {
  title: 'Politique de confidentialité',
  effective: 'En vigueur depuis le 22 mars 2026',
  intro: 'Cette politique de confidentialité s\'applique à Poplist, une application mobile et web créée par Samuel Prigent. Poplist est un service gratuit qui vous permet de créer et partager des listes de films et séries.',
  collectTitle: 'Données collectées',
  collectIntro: 'Nous collectons uniquement les données nécessaires au fonctionnement de l\'application :',
  collectEmail: 'Adresse email (pour la création de compte et l\'authentification)',
  collectUsername: 'Nom d\'utilisateur (choisi par vous, affiché publiquement)',
  collectAvatar: 'Photo de profil (optionnelle, téléchargée par vous)',
  collectLists: 'Vos listes et leur contenu (films et séries que vous ajoutez)',
  collectNoTracking: 'Nous n\'utilisons pas de cookies de suivi. Nous n\'utilisons aucun service d\'analyse. Nous ne collectons pas votre localisation, vos contacts, ni aucune donnée au-delà de ce qui est listé ci-dessus.',
  useTitle: 'Utilisation des données',
  useDescription: 'Vos données sont utilisées exclusivement pour fournir le service Poplist : authentifier votre compte, afficher vos listes et permettre les fonctionnalités de collaboration. Nous ne vendons, ne partageons et ne transmettons vos données à aucun tiers à des fins publicitaires ou d\'analyse.',
  thirdPartyTitle: 'Services tiers',
  thirdPartyIntro: 'L\'application utilise les services tiers suivants :',
  thirdPartyExpo: 'Expo — framework de l\'application mobile et livraison des mises à jour',
  thirdPartyGoogle: 'Google OAuth — authentification (nous recevons uniquement votre email, aucune autre donnée Google)',
  thirdPartyCloudinary: 'Cloudinary — hébergement des images de profil et des couvertures de listes',
  thirdPartyTMDB: 'TMDB — métadonnées des films et séries (aucune donnée utilisateur n\'est partagée avec TMDB)',
  storageTitle: 'Stockage et sécurité',
  storageDescription: 'Vos données sont stockées dans une base de données sécurisée. Toutes les communications entre l\'application et nos serveurs sont chiffrées via HTTPS. Les jetons d\'authentification sont stockés de manière sécurisée sur votre appareil.',
  deletionTitle: 'Suppression des données',
  deletionDescription: 'Vous pouvez supprimer votre compte à tout moment depuis les paramètres de l\'application. Cela supprime définitivement toutes vos données, y compris votre profil, vos listes et le contenu associé. Vous pouvez également demander la suppression de vos données en contactant',
  childrenTitle: 'Enfants',
  childrenDescription: 'Poplist ne s\'adresse pas aux enfants de moins de 13 ans. Nous ne collectons pas sciemment d\'informations personnelles auprès d\'enfants de moins de 13 ans.',
  changesTitle: 'Modifications',
  changesDescription: 'Cette politique de confidentialité peut être mise à jour de temps à autre. Les modifications seront reflétées sur cette page.',
  contactTitle: 'Contact',
  contactDescription: 'Pour toute question concernant cette politique, contactez',
};
