import type { PrivacyContent } from '../../../types/privacy';

export const privacyIt: PrivacyContent = {
  title: 'Informativa sulla Privacy',
  effective: 'In vigore dal: 22 marzo 2026',
  intro: 'Questa informativa sulla privacy si applica a Poplist, un\'applicazione mobile e web creata da Samuel Prigent. Poplist è un servizio gratuito che consente di creare e condividere liste di film e serie TV.',
  collectTitle: 'Dati raccolti',
  collectIntro: 'Raccogliamo solo i dati necessari al funzionamento dell\'applicazione:',
  collectEmail: 'Indirizzo email (per la creazione dell\'account e l\'autenticazione)',
  collectUsername: 'Nome utente (scelto da te, visualizzato pubblicamente)',
  collectAvatar: 'Foto profilo (opzionale, caricata da te)',
  collectLists: 'Le tue liste e il loro contenuto (film e serie che aggiungi)',
  collectNoTracking: 'Non utilizziamo cookie di tracciamento. Non utilizziamo alcun servizio di analisi. Non raccogliamo la tua posizione, i tuoi contatti o altri dati oltre a quelli sopra elencati.',
  useTitle: 'Utilizzo dei dati',
  useDescription: 'I tuoi dati vengono utilizzati esclusivamente per fornire il servizio Poplist: autenticare il tuo account, visualizzare le tue liste e abilitare le funzionalità di collaborazione. Non vendiamo, condividiamo o trasmettiamo i tuoi dati a terzi per scopi pubblicitari o di analisi.',
  thirdPartyTitle: 'Servizi di terze parti',
  thirdPartyIntro: 'L\'applicazione utilizza i seguenti servizi di terze parti:',
  thirdPartyExpo: 'Expo — framework dell\'app mobile e distribuzione degli aggiornamenti',
  thirdPartyGoogle: 'Google OAuth — autenticazione (riceviamo solo la tua email, nessun altro dato Google)',
  thirdPartyCloudinary: 'Cloudinary — hosting delle immagini per foto profilo e copertine delle liste',
  thirdPartyTMDB: 'TMDB — metadati di film e serie (nessun dato utente viene condiviso con TMDB)',
  storageTitle: 'Archiviazione e sicurezza',
  storageDescription: 'I tuoi dati sono archiviati in un database sicuro. Tutte le comunicazioni tra l\'app e i nostri server sono crittografate tramite HTTPS. I token di autenticazione sono archiviati in modo sicuro sul tuo dispositivo.',
  deletionTitle: 'Cancellazione dei dati',
  deletionDescription: 'Puoi eliminare il tuo account in qualsiasi momento dalle impostazioni dell\'app. Questo rimuove permanentemente tutti i tuoi dati, incluso il profilo, le liste e i contenuti associati. Puoi anche richiedere la cancellazione dei dati contattando',
  childrenTitle: 'Minori',
  childrenDescription: 'Poplist non è destinato a minori di 13 anni. Non raccogliamo consapevolmente informazioni personali da minori di 13 anni.',
  changesTitle: 'Modifiche',
  changesDescription: 'Questa Informativa sulla Privacy può essere aggiornata di tanto in tanto. Le modifiche saranno riportate su questa pagina.',
  contactTitle: 'Contatto',
  contactDescription: 'Per qualsiasi domanda riguardo questa informativa, contattare',
};
