import type { PrivacyContent } from '../../../types/privacy';

export const privacyPt: PrivacyContent = {
  title: 'Política de Privacidade',
  effective: 'Em vigor desde: 22 de março de 2026',
  intro: 'Esta política de privacidade aplica-se ao Poplist, uma aplicação móvel e web criada por Samuel Prigent. O Poplist é um serviço gratuito que permite criar e partilhar listas de filmes e séries.',
  collectTitle: 'Dados recolhidos',
  collectIntro: 'Recolhemos apenas os dados necessários ao funcionamento da aplicação:',
  collectEmail: 'Endereço de email (para criação de conta e autenticação)',
  collectUsername: 'Nome de utilizador (escolhido por si, exibido publicamente)',
  collectAvatar: 'Foto de perfil (opcional, carregada por si)',
  collectLists: 'As suas listas e o seu conteúdo (filmes e séries que adiciona)',
  collectNoTracking: 'Não utilizamos cookies de rastreamento. Não utilizamos nenhum serviço de análise. Não recolhemos a sua localização, contactos ou quaisquer outros dados além dos listados acima.',
  useTitle: 'Utilização dos dados',
  useDescription: 'Os seus dados são utilizados exclusivamente para fornecer o serviço Poplist: autenticar a sua conta, exibir as suas listas e permitir funcionalidades de colaboração. Não vendemos, partilhamos ou transmitimos os seus dados a terceiros para fins publicitários ou de análise.',
  thirdPartyTitle: 'Serviços de terceiros',
  thirdPartyIntro: 'A aplicação utiliza os seguintes serviços de terceiros:',
  thirdPartyExpo: 'Expo — framework da aplicação móvel e entrega de atualizações',
  thirdPartyGoogle: 'Google OAuth — autenticação (recebemos apenas o seu email, nenhum outro dado do Google)',
  thirdPartyCloudinary: 'Cloudinary — alojamento de imagens para fotos de perfil e capas de listas',
  thirdPartyTMDB: 'TMDB — metadados de filmes e séries (nenhum dado de utilizador é partilhado com o TMDB)',
  storageTitle: 'Armazenamento e segurança',
  storageDescription: 'Os seus dados são armazenados numa base de dados segura. Todas as comunicações entre a aplicação e os nossos servidores são encriptadas via HTTPS. Os tokens de autenticação são armazenados de forma segura no seu dispositivo.',
  deletionTitle: 'Eliminação de dados',
  deletionDescription: 'Pode eliminar a sua conta a qualquer momento nas definições da aplicação. Isto remove permanentemente todos os seus dados, incluindo o seu perfil, listas e conteúdo associado. Também pode solicitar a eliminação dos seus dados contactando',
  childrenTitle: 'Menores',
  childrenDescription: 'O Poplist não se destina a menores de 13 anos. Não recolhemos conscientemente informações pessoais de menores de 13 anos.',
  changesTitle: 'Alterações',
  changesDescription: 'Esta Política de Privacidade pode ser atualizada de tempos a tempos. As alterações serão refletidas nesta página.',
  contactTitle: 'Contacto',
  contactDescription: 'Para qualquer questão sobre esta política, contacte',
};
